// Code generated by protoc-gen-go. DO NOT EDIT.
// source: standard.proto

package standard

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 状态
type State int32

const (
	State_UNKNOWN              State = 0
	State_SUCCESS              State = 1
	State_FAILURE              State = 2
	State_SERVICE_ERROR        State = 3
	State_PARAMS_INVALID       State = 5
	State_ILLEGAL_REQUEST      State = 6
	State_LABEL_NOT_EXIST      State = 7
	State_USER_NOT_EXIST       State = 8
	State_USER_ALREADY_EXISTS  State = 9
	State_USER_VERIFY_FAILURE  State = 10
	State_LABEL_ALREADY_EXISTS State = 11
	State_DB_OPERATION_FATLURE State = 12
)

var State_name = map[int32]string{
	0:  "UNKNOWN",
	1:  "SUCCESS",
	2:  "FAILURE",
	3:  "SERVICE_ERROR",
	5:  "PARAMS_INVALID",
	6:  "ILLEGAL_REQUEST",
	7:  "LABEL_NOT_EXIST",
	8:  "USER_NOT_EXIST",
	9:  "USER_ALREADY_EXISTS",
	10: "USER_VERIFY_FAILURE",
	11: "LABEL_ALREADY_EXISTS",
	12: "DB_OPERATION_FATLURE",
}

var State_value = map[string]int32{
	"UNKNOWN":              0,
	"SUCCESS":              1,
	"FAILURE":              2,
	"SERVICE_ERROR":        3,
	"PARAMS_INVALID":       5,
	"ILLEGAL_REQUEST":      6,
	"LABEL_NOT_EXIST":      7,
	"USER_NOT_EXIST":       8,
	"USER_ALREADY_EXISTS":  9,
	"USER_VERIFY_FAILURE":  10,
	"LABEL_ALREADY_EXISTS": 11,
	"DB_OPERATION_FATLURE": 12,
}

func (x State) String() string {
	return proto.EnumName(State_name, int32(x))
}

func (State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0b3e239150a6a10f, []int{0}
}

// Label 标签
type Label struct {
	ID                   uint64   `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=Type,proto3" json:"Type,omitempty"`
	State                string   `protobuf:"bytes,3,opt,name=State,proto3" json:"State,omitempty"`
	Value                string   `protobuf:"bytes,4,opt,name=Value,proto3" json:"Value,omitempty"`
	Owner                uint64   `protobuf:"varint,5,opt,name=Owner,proto3" json:"Owner,omitempty"`
	CreateTime           string   `protobuf:"bytes,6,opt,name=CreateTime,proto3" json:"CreateTime,omitempty"`
	UpdateTime           string   `protobuf:"bytes,7,opt,name=UpdateTime,proto3" json:"UpdateTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Label) Reset()         { *m = Label{} }
func (m *Label) String() string { return proto.CompactTextString(m) }
func (*Label) ProtoMessage()    {}
func (*Label) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b3e239150a6a10f, []int{0}
}

func (m *Label) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Label.Unmarshal(m, b)
}
func (m *Label) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Label.Marshal(b, m, deterministic)
}
func (m *Label) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Label.Merge(m, src)
}
func (m *Label) XXX_Size() int {
	return xxx_messageInfo_Label.Size(m)
}
func (m *Label) XXX_DiscardUnknown() {
	xxx_messageInfo_Label.DiscardUnknown(m)
}

var xxx_messageInfo_Label proto.InternalMessageInfo

func (m *Label) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Label) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Label) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *Label) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *Label) GetOwner() uint64 {
	if m != nil {
		return m.Owner
	}
	return 0
}

func (m *Label) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

func (m *Label) GetUpdateTime() string {
	if m != nil {
		return m.UpdateTime
	}
	return ""
}

// User 用户
type User struct {
	ID                   uint64   `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=Type,proto3" json:"Type,omitempty"`
	Avatar               string   `protobuf:"bytes,3,opt,name=Avatar,proto3" json:"Avatar,omitempty"`
	Inviter              uint64   `protobuf:"varint,4,opt,name=Inviter,proto3" json:"Inviter,omitempty"`
	Nickname             string   `protobuf:"bytes,5,opt,name=Nickname,proto3" json:"Nickname,omitempty"`
	Username             string   `protobuf:"bytes,6,opt,name=Username,proto3" json:"Username,omitempty"`
	Password             string   `protobuf:"bytes,7,opt,name=Password,proto3" json:"Password,omitempty"`
	CreateTime           string   `protobuf:"bytes,8,opt,name=CreateTime,proto3" json:"CreateTime,omitempty"`
	UpdateTime           string   `protobuf:"bytes,9,opt,name=UpdateTime,proto3" json:"UpdateTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b3e239150a6a10f, []int{1}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *User) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *User) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *User) GetInviter() uint64 {
	if m != nil {
		return m.Inviter
	}
	return 0
}

func (m *User) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

func (m *User) GetUpdateTime() string {
	if m != nil {
		return m.UpdateTime
	}
	return ""
}

type CreateRequest struct {
	User                 *User    `protobuf:"bytes,1,opt,name=User,proto3" json:"User,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b3e239150a6a10f, []int{2}
}

func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(m, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type CreateResponse struct {
	State                State    `protobuf:"varint,1,opt,name=State,proto3,enum=standard.State" json:"State,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateResponse) Reset()         { *m = CreateResponse{} }
func (m *CreateResponse) String() string { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()    {}
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b3e239150a6a10f, []int{3}
}

func (m *CreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResponse.Unmarshal(m, b)
}
func (m *CreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResponse.Marshal(b, m, deterministic)
}
func (m *CreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResponse.Merge(m, src)
}
func (m *CreateResponse) XXX_Size() int {
	return xxx_messageInfo_CreateResponse.Size(m)
}
func (m *CreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResponse proto.InternalMessageInfo

func (m *CreateResponse) GetState() State {
	if m != nil {
		return m.State
	}
	return State_UNKNOWN
}

func (m *CreateResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type QueryByIDRequest struct {
	ID                   uint64   `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryByIDRequest) Reset()         { *m = QueryByIDRequest{} }
func (m *QueryByIDRequest) String() string { return proto.CompactTextString(m) }
func (*QueryByIDRequest) ProtoMessage()    {}
func (*QueryByIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b3e239150a6a10f, []int{4}
}

func (m *QueryByIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryByIDRequest.Unmarshal(m, b)
}
func (m *QueryByIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryByIDRequest.Marshal(b, m, deterministic)
}
func (m *QueryByIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryByIDRequest.Merge(m, src)
}
func (m *QueryByIDRequest) XXX_Size() int {
	return xxx_messageInfo_QueryByIDRequest.Size(m)
}
func (m *QueryByIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryByIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryByIDRequest proto.InternalMessageInfo

func (m *QueryByIDRequest) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

type QueryByIDResponse struct {
	State                State    `protobuf:"varint,1,opt,name=State,proto3,enum=standard.State" json:"State,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	Data                 *User    `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryByIDResponse) Reset()         { *m = QueryByIDResponse{} }
func (m *QueryByIDResponse) String() string { return proto.CompactTextString(m) }
func (*QueryByIDResponse) ProtoMessage()    {}
func (*QueryByIDResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b3e239150a6a10f, []int{5}
}

func (m *QueryByIDResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryByIDResponse.Unmarshal(m, b)
}
func (m *QueryByIDResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryByIDResponse.Marshal(b, m, deterministic)
}
func (m *QueryByIDResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryByIDResponse.Merge(m, src)
}
func (m *QueryByIDResponse) XXX_Size() int {
	return xxx_messageInfo_QueryByIDResponse.Size(m)
}
func (m *QueryByIDResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryByIDResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryByIDResponse proto.InternalMessageInfo

func (m *QueryByIDResponse) GetState() State {
	if m != nil {
		return m.State
	}
	return State_UNKNOWN
}

func (m *QueryByIDResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *QueryByIDResponse) GetData() *User {
	if m != nil {
		return m.Data
	}
	return nil
}

type UpdateByIDRequest struct {
	ID                   uint64   `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Data                 *User    `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateByIDRequest) Reset()         { *m = UpdateByIDRequest{} }
func (m *UpdateByIDRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateByIDRequest) ProtoMessage()    {}
func (*UpdateByIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b3e239150a6a10f, []int{6}
}

func (m *UpdateByIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateByIDRequest.Unmarshal(m, b)
}
func (m *UpdateByIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateByIDRequest.Marshal(b, m, deterministic)
}
func (m *UpdateByIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateByIDRequest.Merge(m, src)
}
func (m *UpdateByIDRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateByIDRequest.Size(m)
}
func (m *UpdateByIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateByIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateByIDRequest proto.InternalMessageInfo

func (m *UpdateByIDRequest) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *UpdateByIDRequest) GetData() *User {
	if m != nil {
		return m.Data
	}
	return nil
}

type QueryByUsernameRequest struct {
	Username             string   `protobuf:"bytes,3,opt,name=Username,proto3" json:"Username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryByUsernameRequest) Reset()         { *m = QueryByUsernameRequest{} }
func (m *QueryByUsernameRequest) String() string { return proto.CompactTextString(m) }
func (*QueryByUsernameRequest) ProtoMessage()    {}
func (*QueryByUsernameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b3e239150a6a10f, []int{7}
}

func (m *QueryByUsernameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryByUsernameRequest.Unmarshal(m, b)
}
func (m *QueryByUsernameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryByUsernameRequest.Marshal(b, m, deterministic)
}
func (m *QueryByUsernameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryByUsernameRequest.Merge(m, src)
}
func (m *QueryByUsernameRequest) XXX_Size() int {
	return xxx_messageInfo_QueryByUsernameRequest.Size(m)
}
func (m *QueryByUsernameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryByUsernameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryByUsernameRequest proto.InternalMessageInfo

func (m *QueryByUsernameRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type QueryByUsernameResponse struct {
	State                State    `protobuf:"varint,1,opt,name=State,proto3,enum=standard.State" json:"State,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	Data                 *User    `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryByUsernameResponse) Reset()         { *m = QueryByUsernameResponse{} }
func (m *QueryByUsernameResponse) String() string { return proto.CompactTextString(m) }
func (*QueryByUsernameResponse) ProtoMessage()    {}
func (*QueryByUsernameResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b3e239150a6a10f, []int{8}
}

func (m *QueryByUsernameResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryByUsernameResponse.Unmarshal(m, b)
}
func (m *QueryByUsernameResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryByUsernameResponse.Marshal(b, m, deterministic)
}
func (m *QueryByUsernameResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryByUsernameResponse.Merge(m, src)
}
func (m *QueryByUsernameResponse) XXX_Size() int {
	return xxx_messageInfo_QueryByUsernameResponse.Size(m)
}
func (m *QueryByUsernameResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryByUsernameResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryByUsernameResponse proto.InternalMessageInfo

func (m *QueryByUsernameResponse) GetState() State {
	if m != nil {
		return m.State
	}
	return State_UNKNOWN
}

func (m *QueryByUsernameResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *QueryByUsernameResponse) GetData() *User {
	if m != nil {
		return m.Data
	}
	return nil
}

type UpdateByIDResponse struct {
	State                State    `protobuf:"varint,1,opt,name=State,proto3,enum=standard.State" json:"State,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateByIDResponse) Reset()         { *m = UpdateByIDResponse{} }
func (m *UpdateByIDResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateByIDResponse) ProtoMessage()    {}
func (*UpdateByIDResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b3e239150a6a10f, []int{9}
}

func (m *UpdateByIDResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateByIDResponse.Unmarshal(m, b)
}
func (m *UpdateByIDResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateByIDResponse.Marshal(b, m, deterministic)
}
func (m *UpdateByIDResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateByIDResponse.Merge(m, src)
}
func (m *UpdateByIDResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateByIDResponse.Size(m)
}
func (m *UpdateByIDResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateByIDResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateByIDResponse proto.InternalMessageInfo

func (m *UpdateByIDResponse) GetState() State {
	if m != nil {
		return m.State
	}
	return State_UNKNOWN
}

func (m *UpdateByIDResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type DeleteByIDRequest struct {
	ID                   uint64   `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteByIDRequest) Reset()         { *m = DeleteByIDRequest{} }
func (m *DeleteByIDRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteByIDRequest) ProtoMessage()    {}
func (*DeleteByIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b3e239150a6a10f, []int{10}
}

func (m *DeleteByIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteByIDRequest.Unmarshal(m, b)
}
func (m *DeleteByIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteByIDRequest.Marshal(b, m, deterministic)
}
func (m *DeleteByIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteByIDRequest.Merge(m, src)
}
func (m *DeleteByIDRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteByIDRequest.Size(m)
}
func (m *DeleteByIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteByIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteByIDRequest proto.InternalMessageInfo

func (m *DeleteByIDRequest) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

type DeleteByIDResponse struct {
	State                State    `protobuf:"varint,1,opt,name=State,proto3,enum=standard.State" json:"State,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteByIDResponse) Reset()         { *m = DeleteByIDResponse{} }
func (m *DeleteByIDResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteByIDResponse) ProtoMessage()    {}
func (*DeleteByIDResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b3e239150a6a10f, []int{11}
}

func (m *DeleteByIDResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteByIDResponse.Unmarshal(m, b)
}
func (m *DeleteByIDResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteByIDResponse.Marshal(b, m, deterministic)
}
func (m *DeleteByIDResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteByIDResponse.Merge(m, src)
}
func (m *DeleteByIDResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteByIDResponse.Size(m)
}
func (m *DeleteByIDResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteByIDResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteByIDResponse proto.InternalMessageInfo

func (m *DeleteByIDResponse) GetState() State {
	if m != nil {
		return m.State
	}
	return State_UNKNOWN
}

func (m *DeleteByIDResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type UpdatePasswordByIDRequest struct {
	ID                   uint64   `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdatePasswordByIDRequest) Reset()         { *m = UpdatePasswordByIDRequest{} }
func (m *UpdatePasswordByIDRequest) String() string { return proto.CompactTextString(m) }
func (*UpdatePasswordByIDRequest) ProtoMessage()    {}
func (*UpdatePasswordByIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b3e239150a6a10f, []int{12}
}

func (m *UpdatePasswordByIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePasswordByIDRequest.Unmarshal(m, b)
}
func (m *UpdatePasswordByIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePasswordByIDRequest.Marshal(b, m, deterministic)
}
func (m *UpdatePasswordByIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePasswordByIDRequest.Merge(m, src)
}
func (m *UpdatePasswordByIDRequest) XXX_Size() int {
	return xxx_messageInfo_UpdatePasswordByIDRequest.Size(m)
}
func (m *UpdatePasswordByIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePasswordByIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePasswordByIDRequest proto.InternalMessageInfo

func (m *UpdatePasswordByIDRequest) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *UpdatePasswordByIDRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type UpdatePasswordByIDResponse struct {
	State                State    `protobuf:"varint,1,opt,name=State,proto3,enum=standard.State" json:"State,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdatePasswordByIDResponse) Reset()         { *m = UpdatePasswordByIDResponse{} }
func (m *UpdatePasswordByIDResponse) String() string { return proto.CompactTextString(m) }
func (*UpdatePasswordByIDResponse) ProtoMessage()    {}
func (*UpdatePasswordByIDResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b3e239150a6a10f, []int{13}
}

func (m *UpdatePasswordByIDResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePasswordByIDResponse.Unmarshal(m, b)
}
func (m *UpdatePasswordByIDResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePasswordByIDResponse.Marshal(b, m, deterministic)
}
func (m *UpdatePasswordByIDResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePasswordByIDResponse.Merge(m, src)
}
func (m *UpdatePasswordByIDResponse) XXX_Size() int {
	return xxx_messageInfo_UpdatePasswordByIDResponse.Size(m)
}
func (m *UpdatePasswordByIDResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePasswordByIDResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePasswordByIDResponse proto.InternalMessageInfo

func (m *UpdatePasswordByIDResponse) GetState() State {
	if m != nil {
		return m.State
	}
	return State_UNKNOWN
}

func (m *UpdatePasswordByIDResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type VerifyPasswordByIDRequest struct {
	ID                   uint64   `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyPasswordByIDRequest) Reset()         { *m = VerifyPasswordByIDRequest{} }
func (m *VerifyPasswordByIDRequest) String() string { return proto.CompactTextString(m) }
func (*VerifyPasswordByIDRequest) ProtoMessage()    {}
func (*VerifyPasswordByIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b3e239150a6a10f, []int{14}
}

func (m *VerifyPasswordByIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyPasswordByIDRequest.Unmarshal(m, b)
}
func (m *VerifyPasswordByIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyPasswordByIDRequest.Marshal(b, m, deterministic)
}
func (m *VerifyPasswordByIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyPasswordByIDRequest.Merge(m, src)
}
func (m *VerifyPasswordByIDRequest) XXX_Size() int {
	return xxx_messageInfo_VerifyPasswordByIDRequest.Size(m)
}
func (m *VerifyPasswordByIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyPasswordByIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyPasswordByIDRequest proto.InternalMessageInfo

func (m *VerifyPasswordByIDRequest) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *VerifyPasswordByIDRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type VerifyPasswordByIDResponse struct {
	State                State    `protobuf:"varint,1,opt,name=State,proto3,enum=standard.State" json:"State,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	Data                 bool     `protobuf:"varint,3,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyPasswordByIDResponse) Reset()         { *m = VerifyPasswordByIDResponse{} }
func (m *VerifyPasswordByIDResponse) String() string { return proto.CompactTextString(m) }
func (*VerifyPasswordByIDResponse) ProtoMessage()    {}
func (*VerifyPasswordByIDResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b3e239150a6a10f, []int{15}
}

func (m *VerifyPasswordByIDResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyPasswordByIDResponse.Unmarshal(m, b)
}
func (m *VerifyPasswordByIDResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyPasswordByIDResponse.Marshal(b, m, deterministic)
}
func (m *VerifyPasswordByIDResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyPasswordByIDResponse.Merge(m, src)
}
func (m *VerifyPasswordByIDResponse) XXX_Size() int {
	return xxx_messageInfo_VerifyPasswordByIDResponse.Size(m)
}
func (m *VerifyPasswordByIDResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyPasswordByIDResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyPasswordByIDResponse proto.InternalMessageInfo

func (m *VerifyPasswordByIDResponse) GetState() State {
	if m != nil {
		return m.State
	}
	return State_UNKNOWN
}

func (m *VerifyPasswordByIDResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *VerifyPasswordByIDResponse) GetData() bool {
	if m != nil {
		return m.Data
	}
	return false
}

type VerifyPasswordByUsernameRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=Username,proto3" json:"Username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyPasswordByUsernameRequest) Reset()         { *m = VerifyPasswordByUsernameRequest{} }
func (m *VerifyPasswordByUsernameRequest) String() string { return proto.CompactTextString(m) }
func (*VerifyPasswordByUsernameRequest) ProtoMessage()    {}
func (*VerifyPasswordByUsernameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b3e239150a6a10f, []int{16}
}

func (m *VerifyPasswordByUsernameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyPasswordByUsernameRequest.Unmarshal(m, b)
}
func (m *VerifyPasswordByUsernameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyPasswordByUsernameRequest.Marshal(b, m, deterministic)
}
func (m *VerifyPasswordByUsernameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyPasswordByUsernameRequest.Merge(m, src)
}
func (m *VerifyPasswordByUsernameRequest) XXX_Size() int {
	return xxx_messageInfo_VerifyPasswordByUsernameRequest.Size(m)
}
func (m *VerifyPasswordByUsernameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyPasswordByUsernameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyPasswordByUsernameRequest proto.InternalMessageInfo

func (m *VerifyPasswordByUsernameRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *VerifyPasswordByUsernameRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type VerifyPasswordByUsernameResponse struct {
	State                State    `protobuf:"varint,1,opt,name=State,proto3,enum=standard.State" json:"State,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	Data                 bool     `protobuf:"varint,3,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyPasswordByUsernameResponse) Reset()         { *m = VerifyPasswordByUsernameResponse{} }
func (m *VerifyPasswordByUsernameResponse) String() string { return proto.CompactTextString(m) }
func (*VerifyPasswordByUsernameResponse) ProtoMessage()    {}
func (*VerifyPasswordByUsernameResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b3e239150a6a10f, []int{17}
}

func (m *VerifyPasswordByUsernameResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyPasswordByUsernameResponse.Unmarshal(m, b)
}
func (m *VerifyPasswordByUsernameResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyPasswordByUsernameResponse.Marshal(b, m, deterministic)
}
func (m *VerifyPasswordByUsernameResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyPasswordByUsernameResponse.Merge(m, src)
}
func (m *VerifyPasswordByUsernameResponse) XXX_Size() int {
	return xxx_messageInfo_VerifyPasswordByUsernameResponse.Size(m)
}
func (m *VerifyPasswordByUsernameResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyPasswordByUsernameResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyPasswordByUsernameResponse proto.InternalMessageInfo

func (m *VerifyPasswordByUsernameResponse) GetState() State {
	if m != nil {
		return m.State
	}
	return State_UNKNOWN
}

func (m *VerifyPasswordByUsernameResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *VerifyPasswordByUsernameResponse) GetData() bool {
	if m != nil {
		return m.Data
	}
	return false
}

type CreateLabelByOwnerRequest struct {
	Owner                uint64   `protobuf:"varint,1,opt,name=Owner,proto3" json:"Owner,omitempty"`
	Label                *Label   `protobuf:"bytes,2,opt,name=Label,proto3" json:"Label,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateLabelByOwnerRequest) Reset()         { *m = CreateLabelByOwnerRequest{} }
func (m *CreateLabelByOwnerRequest) String() string { return proto.CompactTextString(m) }
func (*CreateLabelByOwnerRequest) ProtoMessage()    {}
func (*CreateLabelByOwnerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b3e239150a6a10f, []int{18}
}

func (m *CreateLabelByOwnerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateLabelByOwnerRequest.Unmarshal(m, b)
}
func (m *CreateLabelByOwnerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateLabelByOwnerRequest.Marshal(b, m, deterministic)
}
func (m *CreateLabelByOwnerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateLabelByOwnerRequest.Merge(m, src)
}
func (m *CreateLabelByOwnerRequest) XXX_Size() int {
	return xxx_messageInfo_CreateLabelByOwnerRequest.Size(m)
}
func (m *CreateLabelByOwnerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateLabelByOwnerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateLabelByOwnerRequest proto.InternalMessageInfo

func (m *CreateLabelByOwnerRequest) GetOwner() uint64 {
	if m != nil {
		return m.Owner
	}
	return 0
}

func (m *CreateLabelByOwnerRequest) GetLabel() *Label {
	if m != nil {
		return m.Label
	}
	return nil
}

type CreateLabelByOwnerResponse struct {
	State                State    `protobuf:"varint,1,opt,name=State,proto3,enum=standard.State" json:"State,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateLabelByOwnerResponse) Reset()         { *m = CreateLabelByOwnerResponse{} }
func (m *CreateLabelByOwnerResponse) String() string { return proto.CompactTextString(m) }
func (*CreateLabelByOwnerResponse) ProtoMessage()    {}
func (*CreateLabelByOwnerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b3e239150a6a10f, []int{19}
}

func (m *CreateLabelByOwnerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateLabelByOwnerResponse.Unmarshal(m, b)
}
func (m *CreateLabelByOwnerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateLabelByOwnerResponse.Marshal(b, m, deterministic)
}
func (m *CreateLabelByOwnerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateLabelByOwnerResponse.Merge(m, src)
}
func (m *CreateLabelByOwnerResponse) XXX_Size() int {
	return xxx_messageInfo_CreateLabelByOwnerResponse.Size(m)
}
func (m *CreateLabelByOwnerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateLabelByOwnerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateLabelByOwnerResponse proto.InternalMessageInfo

func (m *CreateLabelByOwnerResponse) GetState() State {
	if m != nil {
		return m.State
	}
	return State_UNKNOWN
}

func (m *CreateLabelByOwnerResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type QueryLabelByIDRequest struct {
	ID                   uint64   `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryLabelByIDRequest) Reset()         { *m = QueryLabelByIDRequest{} }
func (m *QueryLabelByIDRequest) String() string { return proto.CompactTextString(m) }
func (*QueryLabelByIDRequest) ProtoMessage()    {}
func (*QueryLabelByIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b3e239150a6a10f, []int{20}
}

func (m *QueryLabelByIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryLabelByIDRequest.Unmarshal(m, b)
}
func (m *QueryLabelByIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryLabelByIDRequest.Marshal(b, m, deterministic)
}
func (m *QueryLabelByIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryLabelByIDRequest.Merge(m, src)
}
func (m *QueryLabelByIDRequest) XXX_Size() int {
	return xxx_messageInfo_QueryLabelByIDRequest.Size(m)
}
func (m *QueryLabelByIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryLabelByIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryLabelByIDRequest proto.InternalMessageInfo

func (m *QueryLabelByIDRequest) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

type QueryLabelByIDResponse struct {
	State                State    `protobuf:"varint,1,opt,name=State,proto3,enum=standard.State" json:"State,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	Data                 *Label   `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryLabelByIDResponse) Reset()         { *m = QueryLabelByIDResponse{} }
func (m *QueryLabelByIDResponse) String() string { return proto.CompactTextString(m) }
func (*QueryLabelByIDResponse) ProtoMessage()    {}
func (*QueryLabelByIDResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b3e239150a6a10f, []int{21}
}

func (m *QueryLabelByIDResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryLabelByIDResponse.Unmarshal(m, b)
}
func (m *QueryLabelByIDResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryLabelByIDResponse.Marshal(b, m, deterministic)
}
func (m *QueryLabelByIDResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryLabelByIDResponse.Merge(m, src)
}
func (m *QueryLabelByIDResponse) XXX_Size() int {
	return xxx_messageInfo_QueryLabelByIDResponse.Size(m)
}
func (m *QueryLabelByIDResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryLabelByIDResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryLabelByIDResponse proto.InternalMessageInfo

func (m *QueryLabelByIDResponse) GetState() State {
	if m != nil {
		return m.State
	}
	return State_UNKNOWN
}

func (m *QueryLabelByIDResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *QueryLabelByIDResponse) GetData() *Label {
	if m != nil {
		return m.Data
	}
	return nil
}

type UpdateLabelByIDRequest struct {
	ID                   uint64   `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Data                 *Label   `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateLabelByIDRequest) Reset()         { *m = UpdateLabelByIDRequest{} }
func (m *UpdateLabelByIDRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateLabelByIDRequest) ProtoMessage()    {}
func (*UpdateLabelByIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b3e239150a6a10f, []int{22}
}

func (m *UpdateLabelByIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateLabelByIDRequest.Unmarshal(m, b)
}
func (m *UpdateLabelByIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateLabelByIDRequest.Marshal(b, m, deterministic)
}
func (m *UpdateLabelByIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateLabelByIDRequest.Merge(m, src)
}
func (m *UpdateLabelByIDRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateLabelByIDRequest.Size(m)
}
func (m *UpdateLabelByIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateLabelByIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateLabelByIDRequest proto.InternalMessageInfo

func (m *UpdateLabelByIDRequest) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *UpdateLabelByIDRequest) GetData() *Label {
	if m != nil {
		return m.Data
	}
	return nil
}

type UpdateLabelByIDResponse struct {
	State                State    `protobuf:"varint,1,opt,name=State,proto3,enum=standard.State" json:"State,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateLabelByIDResponse) Reset()         { *m = UpdateLabelByIDResponse{} }
func (m *UpdateLabelByIDResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateLabelByIDResponse) ProtoMessage()    {}
func (*UpdateLabelByIDResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b3e239150a6a10f, []int{23}
}

func (m *UpdateLabelByIDResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateLabelByIDResponse.Unmarshal(m, b)
}
func (m *UpdateLabelByIDResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateLabelByIDResponse.Marshal(b, m, deterministic)
}
func (m *UpdateLabelByIDResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateLabelByIDResponse.Merge(m, src)
}
func (m *UpdateLabelByIDResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateLabelByIDResponse.Size(m)
}
func (m *UpdateLabelByIDResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateLabelByIDResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateLabelByIDResponse proto.InternalMessageInfo

func (m *UpdateLabelByIDResponse) GetState() State {
	if m != nil {
		return m.State
	}
	return State_UNKNOWN
}

func (m *UpdateLabelByIDResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type DeleteLabelByIDRequest struct {
	ID                   uint64   `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteLabelByIDRequest) Reset()         { *m = DeleteLabelByIDRequest{} }
func (m *DeleteLabelByIDRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteLabelByIDRequest) ProtoMessage()    {}
func (*DeleteLabelByIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b3e239150a6a10f, []int{24}
}

func (m *DeleteLabelByIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteLabelByIDRequest.Unmarshal(m, b)
}
func (m *DeleteLabelByIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteLabelByIDRequest.Marshal(b, m, deterministic)
}
func (m *DeleteLabelByIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteLabelByIDRequest.Merge(m, src)
}
func (m *DeleteLabelByIDRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteLabelByIDRequest.Size(m)
}
func (m *DeleteLabelByIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteLabelByIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteLabelByIDRequest proto.InternalMessageInfo

func (m *DeleteLabelByIDRequest) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

type DeleteLabelByIDResponse struct {
	State                State    `protobuf:"varint,1,opt,name=State,proto3,enum=standard.State" json:"State,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteLabelByIDResponse) Reset()         { *m = DeleteLabelByIDResponse{} }
func (m *DeleteLabelByIDResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteLabelByIDResponse) ProtoMessage()    {}
func (*DeleteLabelByIDResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b3e239150a6a10f, []int{25}
}

func (m *DeleteLabelByIDResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteLabelByIDResponse.Unmarshal(m, b)
}
func (m *DeleteLabelByIDResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteLabelByIDResponse.Marshal(b, m, deterministic)
}
func (m *DeleteLabelByIDResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteLabelByIDResponse.Merge(m, src)
}
func (m *DeleteLabelByIDResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteLabelByIDResponse.Size(m)
}
func (m *DeleteLabelByIDResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteLabelByIDResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteLabelByIDResponse proto.InternalMessageInfo

func (m *DeleteLabelByIDResponse) GetState() State {
	if m != nil {
		return m.State
	}
	return State_UNKNOWN
}

func (m *DeleteLabelByIDResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type QueryLabelByOwnerRequest struct {
	Owner                uint64   `protobuf:"varint,1,opt,name=Owner,proto3" json:"Owner,omitempty"`
	Limit                uint64   `protobuf:"varint,2,opt,name=Limit,proto3" json:"Limit,omitempty"`
	Offset               uint64   `protobuf:"varint,3,opt,name=Offset,proto3" json:"Offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryLabelByOwnerRequest) Reset()         { *m = QueryLabelByOwnerRequest{} }
func (m *QueryLabelByOwnerRequest) String() string { return proto.CompactTextString(m) }
func (*QueryLabelByOwnerRequest) ProtoMessage()    {}
func (*QueryLabelByOwnerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b3e239150a6a10f, []int{26}
}

func (m *QueryLabelByOwnerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryLabelByOwnerRequest.Unmarshal(m, b)
}
func (m *QueryLabelByOwnerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryLabelByOwnerRequest.Marshal(b, m, deterministic)
}
func (m *QueryLabelByOwnerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryLabelByOwnerRequest.Merge(m, src)
}
func (m *QueryLabelByOwnerRequest) XXX_Size() int {
	return xxx_messageInfo_QueryLabelByOwnerRequest.Size(m)
}
func (m *QueryLabelByOwnerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryLabelByOwnerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryLabelByOwnerRequest proto.InternalMessageInfo

func (m *QueryLabelByOwnerRequest) GetOwner() uint64 {
	if m != nil {
		return m.Owner
	}
	return 0
}

func (m *QueryLabelByOwnerRequest) GetLimit() uint64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *QueryLabelByOwnerRequest) GetOffset() uint64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type QueryLabelByOwnerResponse struct {
	State                State    `protobuf:"varint,1,opt,name=State,proto3,enum=standard.State" json:"State,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	Total                uint64   `protobuf:"varint,3,opt,name=Total,proto3" json:"Total,omitempty"`
	Data                 []*Label `protobuf:"bytes,4,rep,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryLabelByOwnerResponse) Reset()         { *m = QueryLabelByOwnerResponse{} }
func (m *QueryLabelByOwnerResponse) String() string { return proto.CompactTextString(m) }
func (*QueryLabelByOwnerResponse) ProtoMessage()    {}
func (*QueryLabelByOwnerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b3e239150a6a10f, []int{27}
}

func (m *QueryLabelByOwnerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryLabelByOwnerResponse.Unmarshal(m, b)
}
func (m *QueryLabelByOwnerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryLabelByOwnerResponse.Marshal(b, m, deterministic)
}
func (m *QueryLabelByOwnerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryLabelByOwnerResponse.Merge(m, src)
}
func (m *QueryLabelByOwnerResponse) XXX_Size() int {
	return xxx_messageInfo_QueryLabelByOwnerResponse.Size(m)
}
func (m *QueryLabelByOwnerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryLabelByOwnerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryLabelByOwnerResponse proto.InternalMessageInfo

func (m *QueryLabelByOwnerResponse) GetState() State {
	if m != nil {
		return m.State
	}
	return State_UNKNOWN
}

func (m *QueryLabelByOwnerResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *QueryLabelByOwnerResponse) GetTotal() uint64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *QueryLabelByOwnerResponse) GetData() []*Label {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterEnum("standard.State", State_name, State_value)
	proto.RegisterType((*Label)(nil), "standard.Label")
	proto.RegisterType((*User)(nil), "standard.User")
	proto.RegisterType((*CreateRequest)(nil), "standard.CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "standard.CreateResponse")
	proto.RegisterType((*QueryByIDRequest)(nil), "standard.QueryByIDRequest")
	proto.RegisterType((*QueryByIDResponse)(nil), "standard.QueryByIDResponse")
	proto.RegisterType((*UpdateByIDRequest)(nil), "standard.UpdateByIDRequest")
	proto.RegisterType((*QueryByUsernameRequest)(nil), "standard.QueryByUsernameRequest")
	proto.RegisterType((*QueryByUsernameResponse)(nil), "standard.QueryByUsernameResponse")
	proto.RegisterType((*UpdateByIDResponse)(nil), "standard.UpdateByIDResponse")
	proto.RegisterType((*DeleteByIDRequest)(nil), "standard.DeleteByIDRequest")
	proto.RegisterType((*DeleteByIDResponse)(nil), "standard.DeleteByIDResponse")
	proto.RegisterType((*UpdatePasswordByIDRequest)(nil), "standard.UpdatePasswordByIDRequest")
	proto.RegisterType((*UpdatePasswordByIDResponse)(nil), "standard.UpdatePasswordByIDResponse")
	proto.RegisterType((*VerifyPasswordByIDRequest)(nil), "standard.VerifyPasswordByIDRequest")
	proto.RegisterType((*VerifyPasswordByIDResponse)(nil), "standard.VerifyPasswordByIDResponse")
	proto.RegisterType((*VerifyPasswordByUsernameRequest)(nil), "standard.VerifyPasswordByUsernameRequest")
	proto.RegisterType((*VerifyPasswordByUsernameResponse)(nil), "standard.VerifyPasswordByUsernameResponse")
	proto.RegisterType((*CreateLabelByOwnerRequest)(nil), "standard.CreateLabelByOwnerRequest")
	proto.RegisterType((*CreateLabelByOwnerResponse)(nil), "standard.CreateLabelByOwnerResponse")
	proto.RegisterType((*QueryLabelByIDRequest)(nil), "standard.QueryLabelByIDRequest")
	proto.RegisterType((*QueryLabelByIDResponse)(nil), "standard.QueryLabelByIDResponse")
	proto.RegisterType((*UpdateLabelByIDRequest)(nil), "standard.UpdateLabelByIDRequest")
	proto.RegisterType((*UpdateLabelByIDResponse)(nil), "standard.UpdateLabelByIDResponse")
	proto.RegisterType((*DeleteLabelByIDRequest)(nil), "standard.DeleteLabelByIDRequest")
	proto.RegisterType((*DeleteLabelByIDResponse)(nil), "standard.DeleteLabelByIDResponse")
	proto.RegisterType((*QueryLabelByOwnerRequest)(nil), "standard.QueryLabelByOwnerRequest")
	proto.RegisterType((*QueryLabelByOwnerResponse)(nil), "standard.QueryLabelByOwnerResponse")
}

func init() { proto.RegisterFile("standard.proto", fileDescriptor_0b3e239150a6a10f) }

var fileDescriptor_0b3e239150a6a10f = []byte{
	// 1022 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x57, 0x4b, 0x53, 0xe3, 0x46,
	0x10, 0xb6, 0x8c, 0x9f, 0x4d, 0xd6, 0x88, 0x59, 0x82, 0x85, 0x92, 0xca, 0x3a, 0x22, 0x5b, 0x21,
	0x7b, 0xd8, 0x03, 0x9b, 0x6b, 0x0e, 0x02, 0x0b, 0x4a, 0x15, 0x61, 0xc3, 0xc8, 0x72, 0x60, 0xab,
	0xb2, 0x2e, 0x2d, 0x0c, 0x29, 0x57, 0xc0, 0x66, 0x25, 0xb1, 0xc4, 0x97, 0xbd, 0xe7, 0x17, 0xe4,
	0x57, 0xe4, 0xbf, 0xe5, 0x9a, 0x5b, 0x6a, 0x66, 0x24, 0x79, 0xac, 0x17, 0x54, 0x45, 0xc9, 0xcd,
	0xfd, 0x98, 0xaf, 0x9f, 0xea, 0x6e, 0x43, 0xc7, 0x0f, 0xdc, 0xd9, 0x95, 0xeb, 0x5d, 0xbd, 0xbe,
	0xf3, 0xe6, 0xc1, 0x1c, 0xb5, 0x22, 0x5a, 0xfb, 0x53, 0x82, 0xba, 0xe5, 0xbe, 0x27, 0x37, 0xa8,
	0x03, 0x55, 0xb3, 0xaf, 0x48, 0x3d, 0x69, 0xaf, 0x86, 0xab, 0x66, 0x1f, 0x21, 0xa8, 0x8d, 0x16,
	0x77, 0x44, 0xa9, 0xf6, 0xa4, 0xbd, 0x36, 0x66, 0xbf, 0xd1, 0x16, 0xd4, 0xed, 0xc0, 0x0d, 0x88,
	0xb2, 0xc6, 0x98, 0x9c, 0xa0, 0xdc, 0xb1, 0x7b, 0x73, 0x4f, 0x94, 0x1a, 0xe7, 0x32, 0x82, 0x72,
	0x87, 0x0f, 0x33, 0xe2, 0x29, 0x75, 0x06, 0xc9, 0x09, 0xf4, 0x15, 0xc0, 0xa1, 0x47, 0xdc, 0x80,
	0x8c, 0xa6, 0xb7, 0x44, 0x69, 0xb0, 0x07, 0x02, 0x87, 0xca, 0x9d, 0xbb, 0xab, 0x48, 0xde, 0xe4,
	0xf2, 0x25, 0x47, 0xfb, 0x4b, 0x82, 0x9a, 0xe3, 0x13, 0xef, 0x49, 0xee, 0x6e, 0x43, 0x43, 0xff,
	0xe8, 0x06, 0xae, 0x17, 0xfa, 0x1b, 0x52, 0x48, 0x81, 0xa6, 0x39, 0xfb, 0x38, 0x0d, 0x88, 0xc7,
	0x5c, 0xae, 0xe1, 0x88, 0x44, 0x2a, 0xb4, 0x06, 0xd3, 0xcb, 0x5f, 0x67, 0xee, 0x2d, 0x61, 0x7e,
	0xb7, 0x71, 0x4c, 0x53, 0x19, 0xb5, 0xcc, 0x64, 0xdc, 0xf1, 0x98, 0xa6, 0xb2, 0x53, 0xd7, 0xf7,
	0x1f, 0xe6, 0xde, 0x55, 0xe8, 0x74, 0x4c, 0x27, 0x42, 0x6e, 0x3d, 0x12, 0x72, 0x3b, 0x15, 0xf2,
	0x1b, 0x78, 0xc6, 0xb5, 0x31, 0xf9, 0x70, 0x4f, 0xfc, 0x00, 0x69, 0x3c, 0x05, 0x2c, 0xf8, 0xf5,
	0xfd, 0xce, 0xeb, 0xb8, 0xb8, 0x94, 0x8b, 0x99, 0x4c, 0x3b, 0x83, 0x4e, 0xf4, 0xc8, 0xbf, 0x9b,
	0xcf, 0x7c, 0x82, 0x5e, 0x46, 0xb5, 0xa3, 0xcf, 0x3a, 0xfb, 0x1b, 0xcb, 0x67, 0x8c, 0x1d, 0x15,
	0x53, 0x81, 0xe6, 0x09, 0xf1, 0x7d, 0xf7, 0x97, 0x28, 0x95, 0x11, 0xa9, 0x69, 0x20, 0x9f, 0xdd,
	0x13, 0x6f, 0x71, 0xb0, 0x30, 0xfb, 0x91, 0x2b, 0x89, 0x2a, 0x68, 0xbf, 0xc1, 0xa6, 0xa0, 0x53,
	0x92, 0x65, 0x1a, 0x70, 0xdf, 0x0d, 0x5c, 0x56, 0xc5, 0x8c, 0x80, 0xa9, 0x4c, 0x3b, 0x86, 0x4d,
	0x9e, 0xb3, 0x02, 0xf7, 0x62, 0xa0, 0x6a, 0x01, 0xd0, 0xf7, 0xb0, 0x1d, 0x86, 0x10, 0x55, 0x37,
	0x42, 0x13, 0x1b, 0x60, 0x6d, 0xb5, 0x01, 0xb4, 0x4f, 0xd0, 0x4d, 0xbd, 0xfa, 0x3f, 0xc3, 0x77,
	0x00, 0x89, 0xe1, 0x97, 0x55, 0xf3, 0x5d, 0xd8, 0xec, 0x93, 0x1b, 0x52, 0x98, 0x55, 0x6a, 0x5b,
	0x54, 0x2a, 0xcb, 0xf6, 0x31, 0xec, 0xf0, 0x90, 0xa2, 0x2f, 0xa9, 0xa8, 0xb2, 0xe2, 0x07, 0x58,
	0x5d, 0xfd, 0x00, 0xb5, 0x9f, 0x41, 0xcd, 0x02, 0x2a, 0xd1, 0xcf, 0x31, 0xf1, 0xa6, 0xd7, 0x8b,
	0x7f, 0xeb, 0xe7, 0x07, 0x50, 0xb3, 0x80, 0xca, 0x6a, 0x23, 0x24, 0xb4, 0x51, 0x2b, 0x6c, 0x9b,
	0x0b, 0x78, 0x91, 0x34, 0x59, 0xd4, 0xf5, 0x52, 0xc1, 0xd8, 0x4b, 0x46, 0xf3, 0x00, 0xbd, 0x7c,
	0xe8, 0xff, 0x32, 0xa6, 0x73, 0xd8, 0xe1, 0xa3, 0x8f, 0xed, 0xb5, 0x83, 0x05, 0x5b, 0x3c, 0x51,
	0x34, 0xf1, 0x56, 0x92, 0xc4, 0xad, 0xf4, 0x32, 0x5c, 0x82, 0xe1, 0x60, 0x10, 0xfc, 0x60, 0x6c,
	0xcc, 0xa5, 0xb4, 0x91, 0xb2, 0x90, 0xcb, 0x6a, 0xa4, 0x6f, 0xe1, 0x73, 0x36, 0x43, 0x42, 0xf4,
	0xfc, 0x0f, 0xee, 0x53, 0x38, 0xa2, 0x04, 0xc5, 0xb2, 0x12, 0xba, 0xbb, 0x32, 0x6b, 0x52, 0x89,
	0xe0, 0x19, 0x3e, 0x81, 0x6d, 0xfe, 0x41, 0x3d, 0xe6, 0xe9, 0xd3, 0xe0, 0xde, 0x42, 0x37, 0x05,
	0x57, 0x56, 0x4e, 0xf7, 0x60, 0x9b, 0xcf, 0xa6, 0x47, 0x93, 0xfa, 0x16, 0xba, 0x29, 0xcd, 0xb2,
	0xbc, 0x78, 0x07, 0x8a, 0x58, 0xb0, 0x27, 0x74, 0xe4, 0x16, 0xd4, 0xad, 0xe9, 0xed, 0x34, 0x60,
	0x48, 0x35, 0xcc, 0x09, 0x7a, 0xd0, 0x0c, 0xaf, 0xaf, 0x7d, 0x12, 0xb0, 0x84, 0xd6, 0x70, 0x48,
	0x69, 0x7f, 0x48, 0xb0, 0x93, 0x61, 0xa0, 0xac, 0xa6, 0xd8, 0x82, 0xfa, 0x68, 0x1e, 0xb8, 0x37,
	0xa1, 0x55, 0x4e, 0xc4, 0xb5, 0xad, 0xf5, 0xd6, 0x72, 0x6b, 0xfb, 0xea, 0x6f, 0x29, 0x34, 0x8e,
	0xd6, 0xa1, 0xe9, 0x0c, 0x7e, 0x1c, 0x0c, 0x7f, 0x1a, 0xc8, 0x15, 0x4a, 0xd8, 0xce, 0xe1, 0xa1,
	0x61, 0xdb, 0xb2, 0x44, 0x89, 0x23, 0xdd, 0xb4, 0x1c, 0x6c, 0xc8, 0x55, 0xb4, 0x09, 0xcf, 0x6c,
	0x03, 0x8f, 0xcd, 0x43, 0x63, 0x62, 0x60, 0x3c, 0xc4, 0xf2, 0x1a, 0x42, 0xd0, 0x39, 0xd5, 0xb1,
	0x7e, 0x62, 0x4f, 0xcc, 0xc1, 0x58, 0xb7, 0xcc, 0xbe, 0x5c, 0x47, 0xcf, 0x61, 0xc3, 0xb4, 0x2c,
	0xe3, 0x58, 0xb7, 0x26, 0xd8, 0x38, 0x73, 0x0c, 0x7b, 0x24, 0x37, 0x28, 0xd3, 0xd2, 0x0f, 0x0c,
	0x6b, 0x32, 0x18, 0x8e, 0x26, 0xc6, 0xb9, 0x69, 0x8f, 0xe4, 0x26, 0x7d, 0xed, 0xd8, 0x06, 0x16,
	0x78, 0x2d, 0xd4, 0x85, 0xe7, 0x8c, 0xa7, 0x5b, 0xd8, 0xd0, 0xfb, 0x17, 0x9c, 0x6f, 0xcb, 0xed,
	0x58, 0x30, 0x36, 0xb0, 0x79, 0x74, 0x31, 0x89, 0xdc, 0x02, 0xa4, 0xc0, 0x16, 0x87, 0x4e, 0x3c,
	0x59, 0xa7, 0x92, 0xfe, 0xc1, 0x64, 0x78, 0x6a, 0x60, 0x7d, 0x64, 0x0e, 0x07, 0x93, 0x23, 0x7d,
	0xc4, 0xde, 0x7c, 0xb6, 0xff, 0x7b, 0x1b, 0x9a, 0xfa, 0xe5, 0xe5, 0xfc, 0x7e, 0x16, 0xa0, 0x1f,
	0xa0, 0xc1, 0x47, 0x07, 0xea, 0x2e, 0x13, 0xb5, 0x72, 0xd6, 0xa9, 0x4a, 0x5a, 0xc0, 0x0b, 0xa8,
	0x55, 0xd0, 0x11, 0xb4, 0xe3, 0xbb, 0x0a, 0xa9, 0x4b, 0xc5, 0xe4, 0x41, 0xa6, 0x7e, 0x91, 0x29,
	0x8b, 0x71, 0xcc, 0xe8, 0xd6, 0x64, 0x40, 0x82, 0x72, 0xea, 0x76, 0x52, 0xbf, 0xcc, 0x16, 0x8a,
	0x50, 0xcb, 0xad, 0x2f, 0x42, 0xa5, 0x0e, 0x06, 0x11, 0x2a, 0x7d, 0x28, 0x68, 0x15, 0x74, 0x0e,
	0x1b, 0x89, 0xe3, 0x09, 0xf5, 0x52, 0x71, 0x24, 0xf6, 0x92, 0xfa, 0x75, 0x81, 0x46, 0x8c, 0xec,
	0x46, 0x67, 0x91, 0xb8, 0x52, 0xd1, 0x6e, 0x32, 0xb4, 0x8c, 0xcd, 0xad, 0x7e, 0x53, 0xac, 0x24,
	0x9a, 0x48, 0x6f, 0x6d, 0xd1, 0x44, 0xee, 0x71, 0x20, 0x9a, 0xc8, 0x5f, 0xfc, 0x5a, 0x05, 0xf9,
	0xa0, 0xe4, 0xad, 0x52, 0xf4, 0x5d, 0x3e, 0x46, 0x32, 0x63, 0xaf, 0x9e, 0xa2, 0x1a, 0x1b, 0x75,
	0xa0, 0xb3, 0xba, 0x64, 0xd0, 0x8b, 0x44, 0xc6, 0x93, 0x23, 0x55, 0xed, 0xe5, 0x2b, 0x88, 0xb5,
	0x4e, 0x0c, 0x7b, 0xb1, 0xd6, 0xd9, 0x6b, 0x45, 0xac, 0x75, 0xce, 0xa6, 0xe0, 0xc8, 0x89, 0x01,
	0x2e, 0x22, 0x67, 0x6f, 0x01, 0x11, 0x39, 0x67, 0xfa, 0xf3, 0x12, 0xa7, 0xf7, 0xbe, 0x58, 0xe2,
	0xdc, 0x7b, 0x43, 0x2c, 0x71, 0xfe, 0xe9, 0xa0, 0x55, 0xd0, 0xbb, 0xf0, 0x8f, 0xd3, 0x8a, 0x05,
	0x2d, 0x3b, 0x9f, 0x2b, 0x06, 0x76, 0x0b, 0x75, 0x22, 0xfc, 0xf7, 0x0d, 0xf6, 0xc7, 0xff, 0xcd,
	0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xf6, 0xa3, 0x0b, 0xde, 0x0a, 0x10, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AccountClient is the client API for Account service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AccountClient interface {
	// 用户操作
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
	QueryByID(ctx context.Context, in *QueryByIDRequest, opts ...grpc.CallOption) (*QueryByIDResponse, error)
	UpdateByID(ctx context.Context, in *UpdateByIDRequest, opts ...grpc.CallOption) (*UpdateByIDResponse, error)
	DeleteByID(ctx context.Context, in *DeleteByIDRequest, opts ...grpc.CallOption) (*DeleteByIDResponse, error)
	QueryByUsername(ctx context.Context, in *QueryByUsernameRequest, opts ...grpc.CallOption) (*QueryByUsernameResponse, error)
	UpdatePasswordByID(ctx context.Context, in *UpdatePasswordByIDRequest, opts ...grpc.CallOption) (*UpdatePasswordByIDResponse, error)
	VerifyPasswordByID(ctx context.Context, in *VerifyPasswordByIDRequest, opts ...grpc.CallOption) (*VerifyPasswordByIDResponse, error)
	VerifyPasswordByUsername(ctx context.Context, in *VerifyPasswordByUsernameRequest, opts ...grpc.CallOption) (*VerifyPasswordByUsernameResponse, error)
	// 标签操作
	QueryLabelByID(ctx context.Context, in *QueryLabelByIDRequest, opts ...grpc.CallOption) (*QueryLabelByIDResponse, error)
	UpdateLabelByID(ctx context.Context, in *UpdateLabelByIDRequest, opts ...grpc.CallOption) (*UpdateLabelByIDResponse, error)
	DeleteLabelByID(ctx context.Context, in *DeleteLabelByIDRequest, opts ...grpc.CallOption) (*DeleteLabelByIDResponse, error)
	CreateLabelByOwner(ctx context.Context, in *CreateLabelByOwnerRequest, opts ...grpc.CallOption) (*CreateLabelByOwnerResponse, error)
	QueryLabelByOwner(ctx context.Context, in *QueryLabelByOwnerRequest, opts ...grpc.CallOption) (*QueryLabelByOwnerResponse, error)
}

type accountClient struct {
	cc *grpc.ClientConn
}

func NewAccountClient(cc *grpc.ClientConn) AccountClient {
	return &accountClient{cc}
}

func (c *accountClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, "/standard.Account/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) QueryByID(ctx context.Context, in *QueryByIDRequest, opts ...grpc.CallOption) (*QueryByIDResponse, error) {
	out := new(QueryByIDResponse)
	err := c.cc.Invoke(ctx, "/standard.Account/QueryByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) UpdateByID(ctx context.Context, in *UpdateByIDRequest, opts ...grpc.CallOption) (*UpdateByIDResponse, error) {
	out := new(UpdateByIDResponse)
	err := c.cc.Invoke(ctx, "/standard.Account/UpdateByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) DeleteByID(ctx context.Context, in *DeleteByIDRequest, opts ...grpc.CallOption) (*DeleteByIDResponse, error) {
	out := new(DeleteByIDResponse)
	err := c.cc.Invoke(ctx, "/standard.Account/DeleteByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) QueryByUsername(ctx context.Context, in *QueryByUsernameRequest, opts ...grpc.CallOption) (*QueryByUsernameResponse, error) {
	out := new(QueryByUsernameResponse)
	err := c.cc.Invoke(ctx, "/standard.Account/QueryByUsername", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) UpdatePasswordByID(ctx context.Context, in *UpdatePasswordByIDRequest, opts ...grpc.CallOption) (*UpdatePasswordByIDResponse, error) {
	out := new(UpdatePasswordByIDResponse)
	err := c.cc.Invoke(ctx, "/standard.Account/UpdatePasswordByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) VerifyPasswordByID(ctx context.Context, in *VerifyPasswordByIDRequest, opts ...grpc.CallOption) (*VerifyPasswordByIDResponse, error) {
	out := new(VerifyPasswordByIDResponse)
	err := c.cc.Invoke(ctx, "/standard.Account/VerifyPasswordByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) VerifyPasswordByUsername(ctx context.Context, in *VerifyPasswordByUsernameRequest, opts ...grpc.CallOption) (*VerifyPasswordByUsernameResponse, error) {
	out := new(VerifyPasswordByUsernameResponse)
	err := c.cc.Invoke(ctx, "/standard.Account/VerifyPasswordByUsername", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) QueryLabelByID(ctx context.Context, in *QueryLabelByIDRequest, opts ...grpc.CallOption) (*QueryLabelByIDResponse, error) {
	out := new(QueryLabelByIDResponse)
	err := c.cc.Invoke(ctx, "/standard.Account/QueryLabelByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) UpdateLabelByID(ctx context.Context, in *UpdateLabelByIDRequest, opts ...grpc.CallOption) (*UpdateLabelByIDResponse, error) {
	out := new(UpdateLabelByIDResponse)
	err := c.cc.Invoke(ctx, "/standard.Account/UpdateLabelByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) DeleteLabelByID(ctx context.Context, in *DeleteLabelByIDRequest, opts ...grpc.CallOption) (*DeleteLabelByIDResponse, error) {
	out := new(DeleteLabelByIDResponse)
	err := c.cc.Invoke(ctx, "/standard.Account/DeleteLabelByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) CreateLabelByOwner(ctx context.Context, in *CreateLabelByOwnerRequest, opts ...grpc.CallOption) (*CreateLabelByOwnerResponse, error) {
	out := new(CreateLabelByOwnerResponse)
	err := c.cc.Invoke(ctx, "/standard.Account/CreateLabelByOwner", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) QueryLabelByOwner(ctx context.Context, in *QueryLabelByOwnerRequest, opts ...grpc.CallOption) (*QueryLabelByOwnerResponse, error) {
	out := new(QueryLabelByOwnerResponse)
	err := c.cc.Invoke(ctx, "/standard.Account/QueryLabelByOwner", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountServer is the server API for Account service.
type AccountServer interface {
	// 用户操作
	Create(context.Context, *CreateRequest) (*CreateResponse, error)
	QueryByID(context.Context, *QueryByIDRequest) (*QueryByIDResponse, error)
	UpdateByID(context.Context, *UpdateByIDRequest) (*UpdateByIDResponse, error)
	DeleteByID(context.Context, *DeleteByIDRequest) (*DeleteByIDResponse, error)
	QueryByUsername(context.Context, *QueryByUsernameRequest) (*QueryByUsernameResponse, error)
	UpdatePasswordByID(context.Context, *UpdatePasswordByIDRequest) (*UpdatePasswordByIDResponse, error)
	VerifyPasswordByID(context.Context, *VerifyPasswordByIDRequest) (*VerifyPasswordByIDResponse, error)
	VerifyPasswordByUsername(context.Context, *VerifyPasswordByUsernameRequest) (*VerifyPasswordByUsernameResponse, error)
	// 标签操作
	QueryLabelByID(context.Context, *QueryLabelByIDRequest) (*QueryLabelByIDResponse, error)
	UpdateLabelByID(context.Context, *UpdateLabelByIDRequest) (*UpdateLabelByIDResponse, error)
	DeleteLabelByID(context.Context, *DeleteLabelByIDRequest) (*DeleteLabelByIDResponse, error)
	CreateLabelByOwner(context.Context, *CreateLabelByOwnerRequest) (*CreateLabelByOwnerResponse, error)
	QueryLabelByOwner(context.Context, *QueryLabelByOwnerRequest) (*QueryLabelByOwnerResponse, error)
}

// UnimplementedAccountServer can be embedded to have forward compatible implementations.
type UnimplementedAccountServer struct {
}

func (*UnimplementedAccountServer) Create(ctx context.Context, req *CreateRequest) (*CreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedAccountServer) QueryByID(ctx context.Context, req *QueryByIDRequest) (*QueryByIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryByID not implemented")
}
func (*UnimplementedAccountServer) UpdateByID(ctx context.Context, req *UpdateByIDRequest) (*UpdateByIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateByID not implemented")
}
func (*UnimplementedAccountServer) DeleteByID(ctx context.Context, req *DeleteByIDRequest) (*DeleteByIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteByID not implemented")
}
func (*UnimplementedAccountServer) QueryByUsername(ctx context.Context, req *QueryByUsernameRequest) (*QueryByUsernameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryByUsername not implemented")
}
func (*UnimplementedAccountServer) UpdatePasswordByID(ctx context.Context, req *UpdatePasswordByIDRequest) (*UpdatePasswordByIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePasswordByID not implemented")
}
func (*UnimplementedAccountServer) VerifyPasswordByID(ctx context.Context, req *VerifyPasswordByIDRequest) (*VerifyPasswordByIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyPasswordByID not implemented")
}
func (*UnimplementedAccountServer) VerifyPasswordByUsername(ctx context.Context, req *VerifyPasswordByUsernameRequest) (*VerifyPasswordByUsernameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyPasswordByUsername not implemented")
}
func (*UnimplementedAccountServer) QueryLabelByID(ctx context.Context, req *QueryLabelByIDRequest) (*QueryLabelByIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryLabelByID not implemented")
}
func (*UnimplementedAccountServer) UpdateLabelByID(ctx context.Context, req *UpdateLabelByIDRequest) (*UpdateLabelByIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateLabelByID not implemented")
}
func (*UnimplementedAccountServer) DeleteLabelByID(ctx context.Context, req *DeleteLabelByIDRequest) (*DeleteLabelByIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteLabelByID not implemented")
}
func (*UnimplementedAccountServer) CreateLabelByOwner(ctx context.Context, req *CreateLabelByOwnerRequest) (*CreateLabelByOwnerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateLabelByOwner not implemented")
}
func (*UnimplementedAccountServer) QueryLabelByOwner(ctx context.Context, req *QueryLabelByOwnerRequest) (*QueryLabelByOwnerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryLabelByOwner not implemented")
}

func RegisterAccountServer(s *grpc.Server, srv AccountServer) {
	s.RegisterService(&_Account_serviceDesc, srv)
}

func _Account_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/standard.Account/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Account_QueryByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).QueryByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/standard.Account/QueryByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).QueryByID(ctx, req.(*QueryByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Account_UpdateByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).UpdateByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/standard.Account/UpdateByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).UpdateByID(ctx, req.(*UpdateByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Account_DeleteByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).DeleteByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/standard.Account/DeleteByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).DeleteByID(ctx, req.(*DeleteByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Account_QueryByUsername_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryByUsernameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).QueryByUsername(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/standard.Account/QueryByUsername",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).QueryByUsername(ctx, req.(*QueryByUsernameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Account_UpdatePasswordByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePasswordByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).UpdatePasswordByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/standard.Account/UpdatePasswordByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).UpdatePasswordByID(ctx, req.(*UpdatePasswordByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Account_VerifyPasswordByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyPasswordByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).VerifyPasswordByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/standard.Account/VerifyPasswordByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).VerifyPasswordByID(ctx, req.(*VerifyPasswordByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Account_VerifyPasswordByUsername_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyPasswordByUsernameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).VerifyPasswordByUsername(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/standard.Account/VerifyPasswordByUsername",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).VerifyPasswordByUsername(ctx, req.(*VerifyPasswordByUsernameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Account_QueryLabelByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryLabelByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).QueryLabelByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/standard.Account/QueryLabelByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).QueryLabelByID(ctx, req.(*QueryLabelByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Account_UpdateLabelByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateLabelByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).UpdateLabelByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/standard.Account/UpdateLabelByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).UpdateLabelByID(ctx, req.(*UpdateLabelByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Account_DeleteLabelByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteLabelByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).DeleteLabelByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/standard.Account/DeleteLabelByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).DeleteLabelByID(ctx, req.(*DeleteLabelByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Account_CreateLabelByOwner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLabelByOwnerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).CreateLabelByOwner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/standard.Account/CreateLabelByOwner",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).CreateLabelByOwner(ctx, req.(*CreateLabelByOwnerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Account_QueryLabelByOwner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryLabelByOwnerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).QueryLabelByOwner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/standard.Account/QueryLabelByOwner",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).QueryLabelByOwner(ctx, req.(*QueryLabelByOwnerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Account_serviceDesc = grpc.ServiceDesc{
	ServiceName: "standard.Account",
	HandlerType: (*AccountServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Account_Create_Handler,
		},
		{
			MethodName: "QueryByID",
			Handler:    _Account_QueryByID_Handler,
		},
		{
			MethodName: "UpdateByID",
			Handler:    _Account_UpdateByID_Handler,
		},
		{
			MethodName: "DeleteByID",
			Handler:    _Account_DeleteByID_Handler,
		},
		{
			MethodName: "QueryByUsername",
			Handler:    _Account_QueryByUsername_Handler,
		},
		{
			MethodName: "UpdatePasswordByID",
			Handler:    _Account_UpdatePasswordByID_Handler,
		},
		{
			MethodName: "VerifyPasswordByID",
			Handler:    _Account_VerifyPasswordByID_Handler,
		},
		{
			MethodName: "VerifyPasswordByUsername",
			Handler:    _Account_VerifyPasswordByUsername_Handler,
		},
		{
			MethodName: "QueryLabelByID",
			Handler:    _Account_QueryLabelByID_Handler,
		},
		{
			MethodName: "UpdateLabelByID",
			Handler:    _Account_UpdateLabelByID_Handler,
		},
		{
			MethodName: "DeleteLabelByID",
			Handler:    _Account_DeleteLabelByID_Handler,
		},
		{
			MethodName: "CreateLabelByOwner",
			Handler:    _Account_CreateLabelByOwner_Handler,
		},
		{
			MethodName: "QueryLabelByOwner",
			Handler:    _Account_QueryLabelByOwner_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "standard.proto",
}
