// Code generated by protoc-gen-go. DO NOT EDIT.
// source: standard.proto

package standard

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 状态
type State int32

const (
	State_UNKNOWN              State = 0
	State_SUCCESS              State = 1
	State_FAILURE              State = 2
	State_SERVICE_ERROR        State = 3
	State_PARAMS_INVALID       State = 5
	State_ILLEGAL_REQUEST      State = 6
	State_LABEL_NOT_EXIST      State = 7
	State_USER_NOT_EXIST       State = 8
	State_USER_ALREADY_EXISTS  State = 9
	State_USER_VERIFY_FAILURE  State = 10
	State_LABEL_ALREADY_EXISTS State = 11
	State_DB_OPERATION_FATLURE State = 12
)

var State_name = map[int32]string{
	0:  "UNKNOWN",
	1:  "SUCCESS",
	2:  "FAILURE",
	3:  "SERVICE_ERROR",
	5:  "PARAMS_INVALID",
	6:  "ILLEGAL_REQUEST",
	7:  "LABEL_NOT_EXIST",
	8:  "USER_NOT_EXIST",
	9:  "USER_ALREADY_EXISTS",
	10: "USER_VERIFY_FAILURE",
	11: "LABEL_ALREADY_EXISTS",
	12: "DB_OPERATION_FATLURE",
}

var State_value = map[string]int32{
	"UNKNOWN":              0,
	"SUCCESS":              1,
	"FAILURE":              2,
	"SERVICE_ERROR":        3,
	"PARAMS_INVALID":       5,
	"ILLEGAL_REQUEST":      6,
	"LABEL_NOT_EXIST":      7,
	"USER_NOT_EXIST":       8,
	"USER_ALREADY_EXISTS":  9,
	"USER_VERIFY_FAILURE":  10,
	"LABEL_ALREADY_EXISTS": 11,
	"DB_OPERATION_FATLURE": 12,
}

func (x State) String() string {
	return proto.EnumName(State_name, int32(x))
}

func (State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0b3e239150a6a10f, []int{0}
}

// Label 标签
type Label struct {
	ID                   uint64   `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=Type,proto3" json:"Type,omitempty"`
	State                string   `protobuf:"bytes,3,opt,name=State,proto3" json:"State,omitempty"`
	Value                string   `protobuf:"bytes,4,opt,name=Value,proto3" json:"Value,omitempty"`
	Owner                uint64   `protobuf:"varint,5,opt,name=Owner,proto3" json:"Owner,omitempty"`
	CreateTime           string   `protobuf:"bytes,6,opt,name=CreateTime,proto3" json:"CreateTime,omitempty"`
	UpdateTime           string   `protobuf:"bytes,7,opt,name=UpdateTime,proto3" json:"UpdateTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Label) Reset()         { *m = Label{} }
func (m *Label) String() string { return proto.CompactTextString(m) }
func (*Label) ProtoMessage()    {}
func (*Label) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b3e239150a6a10f, []int{0}
}

func (m *Label) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Label.Unmarshal(m, b)
}
func (m *Label) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Label.Marshal(b, m, deterministic)
}
func (m *Label) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Label.Merge(m, src)
}
func (m *Label) XXX_Size() int {
	return xxx_messageInfo_Label.Size(m)
}
func (m *Label) XXX_DiscardUnknown() {
	xxx_messageInfo_Label.DiscardUnknown(m)
}

var xxx_messageInfo_Label proto.InternalMessageInfo

func (m *Label) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Label) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Label) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *Label) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *Label) GetOwner() uint64 {
	if m != nil {
		return m.Owner
	}
	return 0
}

func (m *Label) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

func (m *Label) GetUpdateTime() string {
	if m != nil {
		return m.UpdateTime
	}
	return ""
}

// User 用户
type User struct {
	ID                   uint64   `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=Type,proto3" json:"Type,omitempty"`
	Avatar               string   `protobuf:"bytes,3,opt,name=Avatar,proto3" json:"Avatar,omitempty"`
	Inviter              uint64   `protobuf:"varint,4,opt,name=Inviter,proto3" json:"Inviter,omitempty"`
	Nickname             string   `protobuf:"bytes,5,opt,name=Nickname,proto3" json:"Nickname,omitempty"`
	Username             string   `protobuf:"bytes,6,opt,name=Username,proto3" json:"Username,omitempty"`
	Password             string   `protobuf:"bytes,7,opt,name=Password,proto3" json:"Password,omitempty"`
	CreateTime           string   `protobuf:"bytes,8,opt,name=CreateTime,proto3" json:"CreateTime,omitempty"`
	UpdateTime           string   `protobuf:"bytes,9,opt,name=UpdateTime,proto3" json:"UpdateTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b3e239150a6a10f, []int{1}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *User) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *User) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *User) GetInviter() uint64 {
	if m != nil {
		return m.Inviter
	}
	return 0
}

func (m *User) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

func (m *User) GetUpdateTime() string {
	if m != nil {
		return m.UpdateTime
	}
	return ""
}

// User 用户
type Group struct {
	ID                   uint64   `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=Type,proto3" json:"Type,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	CreateTime           string   `protobuf:"bytes,4,opt,name=CreateTime,proto3" json:"CreateTime,omitempty"`
	UpdateTime           string   `protobuf:"bytes,5,opt,name=UpdateTime,proto3" json:"UpdateTime,omitempty"`
	Description          string   `protobuf:"bytes,6,opt,name=Description,proto3" json:"Description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Group) Reset()         { *m = Group{} }
func (m *Group) String() string { return proto.CompactTextString(m) }
func (*Group) ProtoMessage()    {}
func (*Group) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b3e239150a6a10f, []int{2}
}

func (m *Group) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Group.Unmarshal(m, b)
}
func (m *Group) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Group.Marshal(b, m, deterministic)
}
func (m *Group) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Group.Merge(m, src)
}
func (m *Group) XXX_Size() int {
	return xxx_messageInfo_Group.Size(m)
}
func (m *Group) XXX_DiscardUnknown() {
	xxx_messageInfo_Group.DiscardUnknown(m)
}

var xxx_messageInfo_Group proto.InternalMessageInfo

func (m *Group) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Group) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Group) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Group) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

func (m *Group) GetUpdateTime() string {
	if m != nil {
		return m.UpdateTime
	}
	return ""
}

func (m *Group) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type CreateUserRequest struct {
	Type                 string   `protobuf:"bytes,1,opt,name=Type,proto3" json:"Type,omitempty"`
	Avatar               string   `protobuf:"bytes,2,opt,name=Avatar,proto3" json:"Avatar,omitempty"`
	Inviter              uint64   `protobuf:"varint,3,opt,name=Inviter,proto3" json:"Inviter,omitempty"`
	Nickname             string   `protobuf:"bytes,4,opt,name=Nickname,proto3" json:"Nickname,omitempty"`
	Username             string   `protobuf:"bytes,5,opt,name=Username,proto3" json:"Username,omitempty"`
	Password             string   `protobuf:"bytes,6,opt,name=Password,proto3" json:"Password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b3e239150a6a10f, []int{3}
}

func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (m *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(m, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *CreateUserRequest) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *CreateUserRequest) GetInviter() uint64 {
	if m != nil {
		return m.Inviter
	}
	return 0
}

func (m *CreateUserRequest) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *CreateUserRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *CreateUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type CreateUserResponse struct {
	State                State    `protobuf:"varint,1,opt,name=State,proto3,enum=standard.State" json:"State,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserResponse) Reset()         { *m = CreateUserResponse{} }
func (m *CreateUserResponse) String() string { return proto.CompactTextString(m) }
func (*CreateUserResponse) ProtoMessage()    {}
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b3e239150a6a10f, []int{4}
}

func (m *CreateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserResponse.Unmarshal(m, b)
}
func (m *CreateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserResponse.Marshal(b, m, deterministic)
}
func (m *CreateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserResponse.Merge(m, src)
}
func (m *CreateUserResponse) XXX_Size() int {
	return xxx_messageInfo_CreateUserResponse.Size(m)
}
func (m *CreateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserResponse proto.InternalMessageInfo

func (m *CreateUserResponse) GetState() State {
	if m != nil {
		return m.State
	}
	return State_UNKNOWN
}

func (m *CreateUserResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type QueryUserByIDRequest struct {
	ID                   uint64   `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryUserByIDRequest) Reset()         { *m = QueryUserByIDRequest{} }
func (m *QueryUserByIDRequest) String() string { return proto.CompactTextString(m) }
func (*QueryUserByIDRequest) ProtoMessage()    {}
func (*QueryUserByIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b3e239150a6a10f, []int{5}
}

func (m *QueryUserByIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryUserByIDRequest.Unmarshal(m, b)
}
func (m *QueryUserByIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryUserByIDRequest.Marshal(b, m, deterministic)
}
func (m *QueryUserByIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryUserByIDRequest.Merge(m, src)
}
func (m *QueryUserByIDRequest) XXX_Size() int {
	return xxx_messageInfo_QueryUserByIDRequest.Size(m)
}
func (m *QueryUserByIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryUserByIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryUserByIDRequest proto.InternalMessageInfo

func (m *QueryUserByIDRequest) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

type QueryUserByIDResponse struct {
	State                State    `protobuf:"varint,1,opt,name=State,proto3,enum=standard.State" json:"State,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	Data                 *User    `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryUserByIDResponse) Reset()         { *m = QueryUserByIDResponse{} }
func (m *QueryUserByIDResponse) String() string { return proto.CompactTextString(m) }
func (*QueryUserByIDResponse) ProtoMessage()    {}
func (*QueryUserByIDResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b3e239150a6a10f, []int{6}
}

func (m *QueryUserByIDResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryUserByIDResponse.Unmarshal(m, b)
}
func (m *QueryUserByIDResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryUserByIDResponse.Marshal(b, m, deterministic)
}
func (m *QueryUserByIDResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryUserByIDResponse.Merge(m, src)
}
func (m *QueryUserByIDResponse) XXX_Size() int {
	return xxx_messageInfo_QueryUserByIDResponse.Size(m)
}
func (m *QueryUserByIDResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryUserByIDResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryUserByIDResponse proto.InternalMessageInfo

func (m *QueryUserByIDResponse) GetState() State {
	if m != nil {
		return m.State
	}
	return State_UNKNOWN
}

func (m *QueryUserByIDResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *QueryUserByIDResponse) GetData() *User {
	if m != nil {
		return m.Data
	}
	return nil
}

type UpdateUserByIDRequest struct {
	ID                   uint64   `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Data                 *User    `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserByIDRequest) Reset()         { *m = UpdateUserByIDRequest{} }
func (m *UpdateUserByIDRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateUserByIDRequest) ProtoMessage()    {}
func (*UpdateUserByIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b3e239150a6a10f, []int{7}
}

func (m *UpdateUserByIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserByIDRequest.Unmarshal(m, b)
}
func (m *UpdateUserByIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserByIDRequest.Marshal(b, m, deterministic)
}
func (m *UpdateUserByIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserByIDRequest.Merge(m, src)
}
func (m *UpdateUserByIDRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateUserByIDRequest.Size(m)
}
func (m *UpdateUserByIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserByIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserByIDRequest proto.InternalMessageInfo

func (m *UpdateUserByIDRequest) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *UpdateUserByIDRequest) GetData() *User {
	if m != nil {
		return m.Data
	}
	return nil
}

type QueryUserByUsernameRequest struct {
	Username             string   `protobuf:"bytes,3,opt,name=Username,proto3" json:"Username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryUserByUsernameRequest) Reset()         { *m = QueryUserByUsernameRequest{} }
func (m *QueryUserByUsernameRequest) String() string { return proto.CompactTextString(m) }
func (*QueryUserByUsernameRequest) ProtoMessage()    {}
func (*QueryUserByUsernameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b3e239150a6a10f, []int{8}
}

func (m *QueryUserByUsernameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryUserByUsernameRequest.Unmarshal(m, b)
}
func (m *QueryUserByUsernameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryUserByUsernameRequest.Marshal(b, m, deterministic)
}
func (m *QueryUserByUsernameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryUserByUsernameRequest.Merge(m, src)
}
func (m *QueryUserByUsernameRequest) XXX_Size() int {
	return xxx_messageInfo_QueryUserByUsernameRequest.Size(m)
}
func (m *QueryUserByUsernameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryUserByUsernameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryUserByUsernameRequest proto.InternalMessageInfo

func (m *QueryUserByUsernameRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type QueryUserByUsernameResponse struct {
	State                State    `protobuf:"varint,1,opt,name=State,proto3,enum=standard.State" json:"State,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	Data                 *User    `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryUserByUsernameResponse) Reset()         { *m = QueryUserByUsernameResponse{} }
func (m *QueryUserByUsernameResponse) String() string { return proto.CompactTextString(m) }
func (*QueryUserByUsernameResponse) ProtoMessage()    {}
func (*QueryUserByUsernameResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b3e239150a6a10f, []int{9}
}

func (m *QueryUserByUsernameResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryUserByUsernameResponse.Unmarshal(m, b)
}
func (m *QueryUserByUsernameResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryUserByUsernameResponse.Marshal(b, m, deterministic)
}
func (m *QueryUserByUsernameResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryUserByUsernameResponse.Merge(m, src)
}
func (m *QueryUserByUsernameResponse) XXX_Size() int {
	return xxx_messageInfo_QueryUserByUsernameResponse.Size(m)
}
func (m *QueryUserByUsernameResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryUserByUsernameResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryUserByUsernameResponse proto.InternalMessageInfo

func (m *QueryUserByUsernameResponse) GetState() State {
	if m != nil {
		return m.State
	}
	return State_UNKNOWN
}

func (m *QueryUserByUsernameResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *QueryUserByUsernameResponse) GetData() *User {
	if m != nil {
		return m.Data
	}
	return nil
}

type UpdateUserByIDResponse struct {
	State                State    `protobuf:"varint,1,opt,name=State,proto3,enum=standard.State" json:"State,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserByIDResponse) Reset()         { *m = UpdateUserByIDResponse{} }
func (m *UpdateUserByIDResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateUserByIDResponse) ProtoMessage()    {}
func (*UpdateUserByIDResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b3e239150a6a10f, []int{10}
}

func (m *UpdateUserByIDResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserByIDResponse.Unmarshal(m, b)
}
func (m *UpdateUserByIDResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserByIDResponse.Marshal(b, m, deterministic)
}
func (m *UpdateUserByIDResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserByIDResponse.Merge(m, src)
}
func (m *UpdateUserByIDResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateUserByIDResponse.Size(m)
}
func (m *UpdateUserByIDResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserByIDResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserByIDResponse proto.InternalMessageInfo

func (m *UpdateUserByIDResponse) GetState() State {
	if m != nil {
		return m.State
	}
	return State_UNKNOWN
}

func (m *UpdateUserByIDResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type DeleteUserByIDRequest struct {
	ID                   uint64   `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserByIDRequest) Reset()         { *m = DeleteUserByIDRequest{} }
func (m *DeleteUserByIDRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteUserByIDRequest) ProtoMessage()    {}
func (*DeleteUserByIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b3e239150a6a10f, []int{11}
}

func (m *DeleteUserByIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserByIDRequest.Unmarshal(m, b)
}
func (m *DeleteUserByIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserByIDRequest.Marshal(b, m, deterministic)
}
func (m *DeleteUserByIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserByIDRequest.Merge(m, src)
}
func (m *DeleteUserByIDRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteUserByIDRequest.Size(m)
}
func (m *DeleteUserByIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserByIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserByIDRequest proto.InternalMessageInfo

func (m *DeleteUserByIDRequest) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

type DeleteUserByIDResponse struct {
	State                State    `protobuf:"varint,1,opt,name=State,proto3,enum=standard.State" json:"State,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserByIDResponse) Reset()         { *m = DeleteUserByIDResponse{} }
func (m *DeleteUserByIDResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteUserByIDResponse) ProtoMessage()    {}
func (*DeleteUserByIDResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b3e239150a6a10f, []int{12}
}

func (m *DeleteUserByIDResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserByIDResponse.Unmarshal(m, b)
}
func (m *DeleteUserByIDResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserByIDResponse.Marshal(b, m, deterministic)
}
func (m *DeleteUserByIDResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserByIDResponse.Merge(m, src)
}
func (m *DeleteUserByIDResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteUserByIDResponse.Size(m)
}
func (m *DeleteUserByIDResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserByIDResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserByIDResponse proto.InternalMessageInfo

func (m *DeleteUserByIDResponse) GetState() State {
	if m != nil {
		return m.State
	}
	return State_UNKNOWN
}

func (m *DeleteUserByIDResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type UpdateUserPasswordByIDRequest struct {
	ID                   uint64   `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserPasswordByIDRequest) Reset()         { *m = UpdateUserPasswordByIDRequest{} }
func (m *UpdateUserPasswordByIDRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateUserPasswordByIDRequest) ProtoMessage()    {}
func (*UpdateUserPasswordByIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b3e239150a6a10f, []int{13}
}

func (m *UpdateUserPasswordByIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserPasswordByIDRequest.Unmarshal(m, b)
}
func (m *UpdateUserPasswordByIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserPasswordByIDRequest.Marshal(b, m, deterministic)
}
func (m *UpdateUserPasswordByIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserPasswordByIDRequest.Merge(m, src)
}
func (m *UpdateUserPasswordByIDRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateUserPasswordByIDRequest.Size(m)
}
func (m *UpdateUserPasswordByIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserPasswordByIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserPasswordByIDRequest proto.InternalMessageInfo

func (m *UpdateUserPasswordByIDRequest) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *UpdateUserPasswordByIDRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type UpdateUserPasswordByIDResponse struct {
	State                State    `protobuf:"varint,1,opt,name=State,proto3,enum=standard.State" json:"State,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserPasswordByIDResponse) Reset()         { *m = UpdateUserPasswordByIDResponse{} }
func (m *UpdateUserPasswordByIDResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateUserPasswordByIDResponse) ProtoMessage()    {}
func (*UpdateUserPasswordByIDResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b3e239150a6a10f, []int{14}
}

func (m *UpdateUserPasswordByIDResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserPasswordByIDResponse.Unmarshal(m, b)
}
func (m *UpdateUserPasswordByIDResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserPasswordByIDResponse.Marshal(b, m, deterministic)
}
func (m *UpdateUserPasswordByIDResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserPasswordByIDResponse.Merge(m, src)
}
func (m *UpdateUserPasswordByIDResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateUserPasswordByIDResponse.Size(m)
}
func (m *UpdateUserPasswordByIDResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserPasswordByIDResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserPasswordByIDResponse proto.InternalMessageInfo

func (m *UpdateUserPasswordByIDResponse) GetState() State {
	if m != nil {
		return m.State
	}
	return State_UNKNOWN
}

func (m *UpdateUserPasswordByIDResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type VerifyUserPasswordByIDRequest struct {
	ID                   uint64   `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyUserPasswordByIDRequest) Reset()         { *m = VerifyUserPasswordByIDRequest{} }
func (m *VerifyUserPasswordByIDRequest) String() string { return proto.CompactTextString(m) }
func (*VerifyUserPasswordByIDRequest) ProtoMessage()    {}
func (*VerifyUserPasswordByIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b3e239150a6a10f, []int{15}
}

func (m *VerifyUserPasswordByIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyUserPasswordByIDRequest.Unmarshal(m, b)
}
func (m *VerifyUserPasswordByIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyUserPasswordByIDRequest.Marshal(b, m, deterministic)
}
func (m *VerifyUserPasswordByIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyUserPasswordByIDRequest.Merge(m, src)
}
func (m *VerifyUserPasswordByIDRequest) XXX_Size() int {
	return xxx_messageInfo_VerifyUserPasswordByIDRequest.Size(m)
}
func (m *VerifyUserPasswordByIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyUserPasswordByIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyUserPasswordByIDRequest proto.InternalMessageInfo

func (m *VerifyUserPasswordByIDRequest) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *VerifyUserPasswordByIDRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type VerifyUserPasswordByIDResponse struct {
	State                State    `protobuf:"varint,1,opt,name=State,proto3,enum=standard.State" json:"State,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	Data                 bool     `protobuf:"varint,3,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyUserPasswordByIDResponse) Reset()         { *m = VerifyUserPasswordByIDResponse{} }
func (m *VerifyUserPasswordByIDResponse) String() string { return proto.CompactTextString(m) }
func (*VerifyUserPasswordByIDResponse) ProtoMessage()    {}
func (*VerifyUserPasswordByIDResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b3e239150a6a10f, []int{16}
}

func (m *VerifyUserPasswordByIDResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyUserPasswordByIDResponse.Unmarshal(m, b)
}
func (m *VerifyUserPasswordByIDResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyUserPasswordByIDResponse.Marshal(b, m, deterministic)
}
func (m *VerifyUserPasswordByIDResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyUserPasswordByIDResponse.Merge(m, src)
}
func (m *VerifyUserPasswordByIDResponse) XXX_Size() int {
	return xxx_messageInfo_VerifyUserPasswordByIDResponse.Size(m)
}
func (m *VerifyUserPasswordByIDResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyUserPasswordByIDResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyUserPasswordByIDResponse proto.InternalMessageInfo

func (m *VerifyUserPasswordByIDResponse) GetState() State {
	if m != nil {
		return m.State
	}
	return State_UNKNOWN
}

func (m *VerifyUserPasswordByIDResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *VerifyUserPasswordByIDResponse) GetData() bool {
	if m != nil {
		return m.Data
	}
	return false
}

type VerifyUserPasswordByUsernameRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=Username,proto3" json:"Username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyUserPasswordByUsernameRequest) Reset()         { *m = VerifyUserPasswordByUsernameRequest{} }
func (m *VerifyUserPasswordByUsernameRequest) String() string { return proto.CompactTextString(m) }
func (*VerifyUserPasswordByUsernameRequest) ProtoMessage()    {}
func (*VerifyUserPasswordByUsernameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b3e239150a6a10f, []int{17}
}

func (m *VerifyUserPasswordByUsernameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyUserPasswordByUsernameRequest.Unmarshal(m, b)
}
func (m *VerifyUserPasswordByUsernameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyUserPasswordByUsernameRequest.Marshal(b, m, deterministic)
}
func (m *VerifyUserPasswordByUsernameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyUserPasswordByUsernameRequest.Merge(m, src)
}
func (m *VerifyUserPasswordByUsernameRequest) XXX_Size() int {
	return xxx_messageInfo_VerifyUserPasswordByUsernameRequest.Size(m)
}
func (m *VerifyUserPasswordByUsernameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyUserPasswordByUsernameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyUserPasswordByUsernameRequest proto.InternalMessageInfo

func (m *VerifyUserPasswordByUsernameRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *VerifyUserPasswordByUsernameRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type VerifyUserPasswordByUsernameResponse struct {
	State                State    `protobuf:"varint,1,opt,name=State,proto3,enum=standard.State" json:"State,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	Data                 bool     `protobuf:"varint,3,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyUserPasswordByUsernameResponse) Reset()         { *m = VerifyUserPasswordByUsernameResponse{} }
func (m *VerifyUserPasswordByUsernameResponse) String() string { return proto.CompactTextString(m) }
func (*VerifyUserPasswordByUsernameResponse) ProtoMessage()    {}
func (*VerifyUserPasswordByUsernameResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b3e239150a6a10f, []int{18}
}

func (m *VerifyUserPasswordByUsernameResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyUserPasswordByUsernameResponse.Unmarshal(m, b)
}
func (m *VerifyUserPasswordByUsernameResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyUserPasswordByUsernameResponse.Marshal(b, m, deterministic)
}
func (m *VerifyUserPasswordByUsernameResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyUserPasswordByUsernameResponse.Merge(m, src)
}
func (m *VerifyUserPasswordByUsernameResponse) XXX_Size() int {
	return xxx_messageInfo_VerifyUserPasswordByUsernameResponse.Size(m)
}
func (m *VerifyUserPasswordByUsernameResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyUserPasswordByUsernameResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyUserPasswordByUsernameResponse proto.InternalMessageInfo

func (m *VerifyUserPasswordByUsernameResponse) GetState() State {
	if m != nil {
		return m.State
	}
	return State_UNKNOWN
}

func (m *VerifyUserPasswordByUsernameResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *VerifyUserPasswordByUsernameResponse) GetData() bool {
	if m != nil {
		return m.Data
	}
	return false
}

type CreateLabelByOwnerRequest struct {
	Owner                uint64   `protobuf:"varint,1,opt,name=Owner,proto3" json:"Owner,omitempty"`
	Label                *Label   `protobuf:"bytes,2,opt,name=Label,proto3" json:"Label,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateLabelByOwnerRequest) Reset()         { *m = CreateLabelByOwnerRequest{} }
func (m *CreateLabelByOwnerRequest) String() string { return proto.CompactTextString(m) }
func (*CreateLabelByOwnerRequest) ProtoMessage()    {}
func (*CreateLabelByOwnerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b3e239150a6a10f, []int{19}
}

func (m *CreateLabelByOwnerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateLabelByOwnerRequest.Unmarshal(m, b)
}
func (m *CreateLabelByOwnerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateLabelByOwnerRequest.Marshal(b, m, deterministic)
}
func (m *CreateLabelByOwnerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateLabelByOwnerRequest.Merge(m, src)
}
func (m *CreateLabelByOwnerRequest) XXX_Size() int {
	return xxx_messageInfo_CreateLabelByOwnerRequest.Size(m)
}
func (m *CreateLabelByOwnerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateLabelByOwnerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateLabelByOwnerRequest proto.InternalMessageInfo

func (m *CreateLabelByOwnerRequest) GetOwner() uint64 {
	if m != nil {
		return m.Owner
	}
	return 0
}

func (m *CreateLabelByOwnerRequest) GetLabel() *Label {
	if m != nil {
		return m.Label
	}
	return nil
}

type CreateLabelByOwnerResponse struct {
	State                State    `protobuf:"varint,1,opt,name=State,proto3,enum=standard.State" json:"State,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateLabelByOwnerResponse) Reset()         { *m = CreateLabelByOwnerResponse{} }
func (m *CreateLabelByOwnerResponse) String() string { return proto.CompactTextString(m) }
func (*CreateLabelByOwnerResponse) ProtoMessage()    {}
func (*CreateLabelByOwnerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b3e239150a6a10f, []int{20}
}

func (m *CreateLabelByOwnerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateLabelByOwnerResponse.Unmarshal(m, b)
}
func (m *CreateLabelByOwnerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateLabelByOwnerResponse.Marshal(b, m, deterministic)
}
func (m *CreateLabelByOwnerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateLabelByOwnerResponse.Merge(m, src)
}
func (m *CreateLabelByOwnerResponse) XXX_Size() int {
	return xxx_messageInfo_CreateLabelByOwnerResponse.Size(m)
}
func (m *CreateLabelByOwnerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateLabelByOwnerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateLabelByOwnerResponse proto.InternalMessageInfo

func (m *CreateLabelByOwnerResponse) GetState() State {
	if m != nil {
		return m.State
	}
	return State_UNKNOWN
}

func (m *CreateLabelByOwnerResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type QueryLabelByIDRequest struct {
	ID                   uint64   `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryLabelByIDRequest) Reset()         { *m = QueryLabelByIDRequest{} }
func (m *QueryLabelByIDRequest) String() string { return proto.CompactTextString(m) }
func (*QueryLabelByIDRequest) ProtoMessage()    {}
func (*QueryLabelByIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b3e239150a6a10f, []int{21}
}

func (m *QueryLabelByIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryLabelByIDRequest.Unmarshal(m, b)
}
func (m *QueryLabelByIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryLabelByIDRequest.Marshal(b, m, deterministic)
}
func (m *QueryLabelByIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryLabelByIDRequest.Merge(m, src)
}
func (m *QueryLabelByIDRequest) XXX_Size() int {
	return xxx_messageInfo_QueryLabelByIDRequest.Size(m)
}
func (m *QueryLabelByIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryLabelByIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryLabelByIDRequest proto.InternalMessageInfo

func (m *QueryLabelByIDRequest) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

type QueryLabelByIDResponse struct {
	State                State    `protobuf:"varint,1,opt,name=State,proto3,enum=standard.State" json:"State,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	Data                 *Label   `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryLabelByIDResponse) Reset()         { *m = QueryLabelByIDResponse{} }
func (m *QueryLabelByIDResponse) String() string { return proto.CompactTextString(m) }
func (*QueryLabelByIDResponse) ProtoMessage()    {}
func (*QueryLabelByIDResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b3e239150a6a10f, []int{22}
}

func (m *QueryLabelByIDResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryLabelByIDResponse.Unmarshal(m, b)
}
func (m *QueryLabelByIDResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryLabelByIDResponse.Marshal(b, m, deterministic)
}
func (m *QueryLabelByIDResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryLabelByIDResponse.Merge(m, src)
}
func (m *QueryLabelByIDResponse) XXX_Size() int {
	return xxx_messageInfo_QueryLabelByIDResponse.Size(m)
}
func (m *QueryLabelByIDResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryLabelByIDResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryLabelByIDResponse proto.InternalMessageInfo

func (m *QueryLabelByIDResponse) GetState() State {
	if m != nil {
		return m.State
	}
	return State_UNKNOWN
}

func (m *QueryLabelByIDResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *QueryLabelByIDResponse) GetData() *Label {
	if m != nil {
		return m.Data
	}
	return nil
}

type UpdateLabelByIDRequest struct {
	ID                   uint64   `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Data                 *Label   `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateLabelByIDRequest) Reset()         { *m = UpdateLabelByIDRequest{} }
func (m *UpdateLabelByIDRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateLabelByIDRequest) ProtoMessage()    {}
func (*UpdateLabelByIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b3e239150a6a10f, []int{23}
}

func (m *UpdateLabelByIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateLabelByIDRequest.Unmarshal(m, b)
}
func (m *UpdateLabelByIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateLabelByIDRequest.Marshal(b, m, deterministic)
}
func (m *UpdateLabelByIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateLabelByIDRequest.Merge(m, src)
}
func (m *UpdateLabelByIDRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateLabelByIDRequest.Size(m)
}
func (m *UpdateLabelByIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateLabelByIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateLabelByIDRequest proto.InternalMessageInfo

func (m *UpdateLabelByIDRequest) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *UpdateLabelByIDRequest) GetData() *Label {
	if m != nil {
		return m.Data
	}
	return nil
}

type UpdateLabelByIDResponse struct {
	State                State    `protobuf:"varint,1,opt,name=State,proto3,enum=standard.State" json:"State,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateLabelByIDResponse) Reset()         { *m = UpdateLabelByIDResponse{} }
func (m *UpdateLabelByIDResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateLabelByIDResponse) ProtoMessage()    {}
func (*UpdateLabelByIDResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b3e239150a6a10f, []int{24}
}

func (m *UpdateLabelByIDResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateLabelByIDResponse.Unmarshal(m, b)
}
func (m *UpdateLabelByIDResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateLabelByIDResponse.Marshal(b, m, deterministic)
}
func (m *UpdateLabelByIDResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateLabelByIDResponse.Merge(m, src)
}
func (m *UpdateLabelByIDResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateLabelByIDResponse.Size(m)
}
func (m *UpdateLabelByIDResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateLabelByIDResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateLabelByIDResponse proto.InternalMessageInfo

func (m *UpdateLabelByIDResponse) GetState() State {
	if m != nil {
		return m.State
	}
	return State_UNKNOWN
}

func (m *UpdateLabelByIDResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type DeleteLabelByIDRequest struct {
	ID                   uint64   `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteLabelByIDRequest) Reset()         { *m = DeleteLabelByIDRequest{} }
func (m *DeleteLabelByIDRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteLabelByIDRequest) ProtoMessage()    {}
func (*DeleteLabelByIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b3e239150a6a10f, []int{25}
}

func (m *DeleteLabelByIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteLabelByIDRequest.Unmarshal(m, b)
}
func (m *DeleteLabelByIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteLabelByIDRequest.Marshal(b, m, deterministic)
}
func (m *DeleteLabelByIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteLabelByIDRequest.Merge(m, src)
}
func (m *DeleteLabelByIDRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteLabelByIDRequest.Size(m)
}
func (m *DeleteLabelByIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteLabelByIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteLabelByIDRequest proto.InternalMessageInfo

func (m *DeleteLabelByIDRequest) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

type DeleteLabelByIDResponse struct {
	State                State    `protobuf:"varint,1,opt,name=State,proto3,enum=standard.State" json:"State,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteLabelByIDResponse) Reset()         { *m = DeleteLabelByIDResponse{} }
func (m *DeleteLabelByIDResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteLabelByIDResponse) ProtoMessage()    {}
func (*DeleteLabelByIDResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b3e239150a6a10f, []int{26}
}

func (m *DeleteLabelByIDResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteLabelByIDResponse.Unmarshal(m, b)
}
func (m *DeleteLabelByIDResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteLabelByIDResponse.Marshal(b, m, deterministic)
}
func (m *DeleteLabelByIDResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteLabelByIDResponse.Merge(m, src)
}
func (m *DeleteLabelByIDResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteLabelByIDResponse.Size(m)
}
func (m *DeleteLabelByIDResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteLabelByIDResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteLabelByIDResponse proto.InternalMessageInfo

func (m *DeleteLabelByIDResponse) GetState() State {
	if m != nil {
		return m.State
	}
	return State_UNKNOWN
}

func (m *DeleteLabelByIDResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type QueryLabelByOwnerRequest struct {
	Owner                uint64   `protobuf:"varint,1,opt,name=Owner,proto3" json:"Owner,omitempty"`
	Limit                uint64   `protobuf:"varint,2,opt,name=Limit,proto3" json:"Limit,omitempty"`
	Offset               uint64   `protobuf:"varint,3,opt,name=Offset,proto3" json:"Offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryLabelByOwnerRequest) Reset()         { *m = QueryLabelByOwnerRequest{} }
func (m *QueryLabelByOwnerRequest) String() string { return proto.CompactTextString(m) }
func (*QueryLabelByOwnerRequest) ProtoMessage()    {}
func (*QueryLabelByOwnerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b3e239150a6a10f, []int{27}
}

func (m *QueryLabelByOwnerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryLabelByOwnerRequest.Unmarshal(m, b)
}
func (m *QueryLabelByOwnerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryLabelByOwnerRequest.Marshal(b, m, deterministic)
}
func (m *QueryLabelByOwnerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryLabelByOwnerRequest.Merge(m, src)
}
func (m *QueryLabelByOwnerRequest) XXX_Size() int {
	return xxx_messageInfo_QueryLabelByOwnerRequest.Size(m)
}
func (m *QueryLabelByOwnerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryLabelByOwnerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryLabelByOwnerRequest proto.InternalMessageInfo

func (m *QueryLabelByOwnerRequest) GetOwner() uint64 {
	if m != nil {
		return m.Owner
	}
	return 0
}

func (m *QueryLabelByOwnerRequest) GetLimit() uint64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *QueryLabelByOwnerRequest) GetOffset() uint64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type QueryLabelByOwnerResponse struct {
	State                State    `protobuf:"varint,1,opt,name=State,proto3,enum=standard.State" json:"State,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	Total                uint64   `protobuf:"varint,3,opt,name=Total,proto3" json:"Total,omitempty"`
	Data                 []*Label `protobuf:"bytes,4,rep,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryLabelByOwnerResponse) Reset()         { *m = QueryLabelByOwnerResponse{} }
func (m *QueryLabelByOwnerResponse) String() string { return proto.CompactTextString(m) }
func (*QueryLabelByOwnerResponse) ProtoMessage()    {}
func (*QueryLabelByOwnerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b3e239150a6a10f, []int{28}
}

func (m *QueryLabelByOwnerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryLabelByOwnerResponse.Unmarshal(m, b)
}
func (m *QueryLabelByOwnerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryLabelByOwnerResponse.Marshal(b, m, deterministic)
}
func (m *QueryLabelByOwnerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryLabelByOwnerResponse.Merge(m, src)
}
func (m *QueryLabelByOwnerResponse) XXX_Size() int {
	return xxx_messageInfo_QueryLabelByOwnerResponse.Size(m)
}
func (m *QueryLabelByOwnerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryLabelByOwnerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryLabelByOwnerResponse proto.InternalMessageInfo

func (m *QueryLabelByOwnerResponse) GetState() State {
	if m != nil {
		return m.State
	}
	return State_UNKNOWN
}

func (m *QueryLabelByOwnerResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *QueryLabelByOwnerResponse) GetTotal() uint64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *QueryLabelByOwnerResponse) GetData() []*Label {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterEnum("standard.State", State_name, State_value)
	proto.RegisterType((*Label)(nil), "standard.Label")
	proto.RegisterType((*User)(nil), "standard.User")
	proto.RegisterType((*Group)(nil), "standard.Group")
	proto.RegisterType((*CreateUserRequest)(nil), "standard.CreateUserRequest")
	proto.RegisterType((*CreateUserResponse)(nil), "standard.CreateUserResponse")
	proto.RegisterType((*QueryUserByIDRequest)(nil), "standard.QueryUserByIDRequest")
	proto.RegisterType((*QueryUserByIDResponse)(nil), "standard.QueryUserByIDResponse")
	proto.RegisterType((*UpdateUserByIDRequest)(nil), "standard.UpdateUserByIDRequest")
	proto.RegisterType((*QueryUserByUsernameRequest)(nil), "standard.QueryUserByUsernameRequest")
	proto.RegisterType((*QueryUserByUsernameResponse)(nil), "standard.QueryUserByUsernameResponse")
	proto.RegisterType((*UpdateUserByIDResponse)(nil), "standard.UpdateUserByIDResponse")
	proto.RegisterType((*DeleteUserByIDRequest)(nil), "standard.DeleteUserByIDRequest")
	proto.RegisterType((*DeleteUserByIDResponse)(nil), "standard.DeleteUserByIDResponse")
	proto.RegisterType((*UpdateUserPasswordByIDRequest)(nil), "standard.UpdateUserPasswordByIDRequest")
	proto.RegisterType((*UpdateUserPasswordByIDResponse)(nil), "standard.UpdateUserPasswordByIDResponse")
	proto.RegisterType((*VerifyUserPasswordByIDRequest)(nil), "standard.VerifyUserPasswordByIDRequest")
	proto.RegisterType((*VerifyUserPasswordByIDResponse)(nil), "standard.VerifyUserPasswordByIDResponse")
	proto.RegisterType((*VerifyUserPasswordByUsernameRequest)(nil), "standard.VerifyUserPasswordByUsernameRequest")
	proto.RegisterType((*VerifyUserPasswordByUsernameResponse)(nil), "standard.VerifyUserPasswordByUsernameResponse")
	proto.RegisterType((*CreateLabelByOwnerRequest)(nil), "standard.CreateLabelByOwnerRequest")
	proto.RegisterType((*CreateLabelByOwnerResponse)(nil), "standard.CreateLabelByOwnerResponse")
	proto.RegisterType((*QueryLabelByIDRequest)(nil), "standard.QueryLabelByIDRequest")
	proto.RegisterType((*QueryLabelByIDResponse)(nil), "standard.QueryLabelByIDResponse")
	proto.RegisterType((*UpdateLabelByIDRequest)(nil), "standard.UpdateLabelByIDRequest")
	proto.RegisterType((*UpdateLabelByIDResponse)(nil), "standard.UpdateLabelByIDResponse")
	proto.RegisterType((*DeleteLabelByIDRequest)(nil), "standard.DeleteLabelByIDRequest")
	proto.RegisterType((*DeleteLabelByIDResponse)(nil), "standard.DeleteLabelByIDResponse")
	proto.RegisterType((*QueryLabelByOwnerRequest)(nil), "standard.QueryLabelByOwnerRequest")
	proto.RegisterType((*QueryLabelByOwnerResponse)(nil), "standard.QueryLabelByOwnerResponse")
}

func init() { proto.RegisterFile("standard.proto", fileDescriptor_0b3e239150a6a10f) }

var fileDescriptor_0b3e239150a6a10f = []byte{
	// 1093 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x58, 0x4f, 0x4f, 0xe3, 0x46,
	0x14, 0x8f, 0x13, 0xe7, 0xdf, 0xa3, 0x1b, 0xc2, 0x10, 0xc0, 0x9b, 0xdd, 0xd2, 0xd4, 0x40, 0x17,
	0x55, 0x2a, 0x07, 0x7a, 0xe9, 0xd5, 0x10, 0xb3, 0xb2, 0x30, 0x09, 0x3b, 0x4e, 0x52, 0x58, 0x69,
	0x37, 0xf2, 0x92, 0xa1, 0x8a, 0x0a, 0x49, 0x6a, 0x3b, 0x8b, 0xa2, 0x56, 0xad, 0xd4, 0x2f, 0xd1,
	0x73, 0x3f, 0x40, 0x3f, 0x58, 0x6f, 0xbd, 0xf6, 0x56, 0x79, 0xfc, 0x27, 0x13, 0x67, 0xec, 0xe4,
	0xe0, 0xee, 0x8d, 0xf7, 0xde, 0xcc, 0xef, 0xfd, 0xde, 0x1f, 0xcf, 0x7b, 0x01, 0x2a, 0xb6, 0x63,
	0x8e, 0x06, 0xa6, 0x35, 0x38, 0x99, 0x58, 0x63, 0x67, 0x8c, 0x4a, 0x81, 0x2c, 0xff, 0x25, 0x40,
	0x5e, 0x37, 0x3f, 0x90, 0x07, 0x54, 0x81, 0xac, 0xd6, 0x94, 0x84, 0x86, 0x70, 0x2c, 0xe2, 0xac,
	0xd6, 0x44, 0x08, 0xc4, 0xce, 0x6c, 0x42, 0xa4, 0x6c, 0x43, 0x38, 0x2e, 0x63, 0xfa, 0x37, 0xaa,
	0x41, 0xde, 0x70, 0x4c, 0x87, 0x48, 0x39, 0xaa, 0xf4, 0x04, 0x57, 0xdb, 0x33, 0x1f, 0xa6, 0x44,
	0x12, 0x3d, 0x2d, 0x15, 0x5c, 0x6d, 0xfb, 0x69, 0x44, 0x2c, 0x29, 0x4f, 0x21, 0x3d, 0x01, 0xed,
	0x03, 0x9c, 0x5b, 0xc4, 0x74, 0x48, 0x67, 0xf8, 0x48, 0xa4, 0x02, 0xbd, 0xc0, 0x68, 0x5c, 0x7b,
	0x77, 0x32, 0x08, 0xec, 0x45, 0xcf, 0x3e, 0xd7, 0xc8, 0xff, 0x08, 0x20, 0x76, 0x6d, 0x62, 0xad,
	0x45, 0x77, 0x17, 0x0a, 0xca, 0x47, 0xd3, 0x31, 0x2d, 0x9f, 0xaf, 0x2f, 0x21, 0x09, 0x8a, 0xda,
	0xe8, 0xe3, 0xd0, 0x21, 0x16, 0xa5, 0x2c, 0xe2, 0x40, 0x44, 0x75, 0x28, 0xb5, 0x86, 0x77, 0x3f,
	0x8e, 0xcc, 0x47, 0x42, 0x79, 0x97, 0x71, 0x28, 0xbb, 0x36, 0xd7, 0x33, 0xb5, 0x79, 0xc4, 0x43,
	0xd9, 0xb5, 0x5d, 0x9b, 0xb6, 0xfd, 0x34, 0xb6, 0x06, 0x3e, 0xe9, 0x50, 0x8e, 0x84, 0x5c, 0x5a,
	0x11, 0x72, 0x79, 0x29, 0xe4, 0x3f, 0x05, 0xc8, 0xbf, 0xb6, 0xc6, 0xd3, 0xc9, 0x5a, 0x31, 0x23,
	0x10, 0x5b, 0x2e, 0x43, 0x2f, 0x62, 0xfa, 0x77, 0x84, 0x81, 0xb8, 0x82, 0x41, 0x3e, 0xca, 0x00,
	0x35, 0x60, 0xa3, 0x49, 0xec, 0x3b, 0x6b, 0x38, 0x71, 0x86, 0xe3, 0x91, 0x1f, 0x3c, 0xab, 0x72,
	0xdb, 0x68, 0xcb, 0x03, 0x74, 0x53, 0x82, 0xc9, 0x4f, 0x53, 0x62, 0x3b, 0x21, 0x3f, 0x81, 0x5b,
	0x93, 0x6c, 0x5c, 0x4d, 0x72, 0xf1, 0x35, 0x11, 0x13, 0x6a, 0x92, 0x4f, 0xa8, 0x49, 0x61, 0xb1,
	0x26, 0x72, 0x17, 0x10, 0x4b, 0xd7, 0x9e, 0x8c, 0x47, 0x36, 0x41, 0x47, 0x41, 0x7b, 0xbb, 0x84,
	0x2b, 0xa7, 0x9b, 0x27, 0xe1, 0x67, 0x43, 0xd5, 0x41, 0xbf, 0x4b, 0x50, 0xbc, 0x22, 0xb6, 0x6d,
	0xfe, 0x10, 0x64, 0x3e, 0x10, 0xe5, 0xaf, 0xa0, 0xf6, 0x66, 0x4a, 0xac, 0x99, 0x8b, 0x7a, 0x36,
	0xd3, 0x9a, 0x41, 0x22, 0x22, 0x85, 0x93, 0x7f, 0x81, 0x9d, 0xc8, 0xb9, 0x94, 0x18, 0x20, 0x19,
	0xc4, 0xa6, 0xe9, 0x98, 0x34, 0x87, 0x1b, 0xa7, 0x95, 0xf9, 0x7d, 0x1a, 0x28, 0xb5, 0xc9, 0x97,
	0xb0, 0xe3, 0x15, 0x77, 0x05, 0xcd, 0x10, 0x2c, 0x9b, 0x00, 0xf6, 0x1d, 0xd4, 0x99, 0x50, 0x82,
	0xe4, 0x07, 0x88, 0x6c, 0x7d, 0x72, 0x8b, 0xf5, 0x91, 0x7f, 0x17, 0xe0, 0x05, 0xf7, 0xea, 0xa7,
	0xcc, 0xc5, 0x2d, 0xec, 0x46, 0x73, 0x91, 0x56, 0x33, 0xbc, 0x82, 0x9d, 0x26, 0x79, 0x20, 0x2b,
	0xd3, 0xec, 0x72, 0x88, 0x1e, 0x4c, 0x8b, 0xc3, 0x25, 0x7c, 0x3e, 0x0f, 0x2f, 0xe8, 0xfe, 0xa4,
	0x92, 0xb3, 0x1f, 0x4d, 0x36, 0xf2, 0xd1, 0x98, 0xb0, 0x1f, 0x07, 0x96, 0x22, 0xdf, 0x1e, 0xb1,
	0x86, 0xf7, 0xb3, 0x34, 0xf8, 0x4e, 0x61, 0x3f, 0x0e, 0x2c, 0xad, 0x16, 0x43, 0x4c, 0x8b, 0x95,
	0xfc, 0x96, 0x7a, 0x07, 0x07, 0x3c, 0xb7, 0x49, 0x9f, 0x86, 0x90, 0xf0, 0x74, 0x45, 0xa3, 0xfa,
	0x19, 0x0e, 0x93, 0xe1, 0xff, 0xcf, 0xd8, 0x6e, 0xe0, 0xb9, 0xf7, 0x6e, 0xd2, 0x9d, 0xe1, 0x6c,
	0x46, 0x87, 0x7a, 0x10, 0x51, 0x38, 0xf1, 0x05, 0x76, 0xe2, 0x1f, 0xf9, 0x0b, 0x86, 0xff, 0x8a,
	0x30, 0x3c, 0xa8, 0x1a, 0x7b, 0x56, 0xf9, 0x1d, 0xd4, 0x79, 0xc8, 0x29, 0x7e, 0x8c, 0xf4, 0xad,
	0xf1, 0xd1, 0xe3, 0x3f, 0xc6, 0x5f, 0x61, 0x37, 0x7a, 0x30, 0xad, 0x84, 0x1e, 0x2c, 0xbc, 0x47,
	0x4b, 0x89, 0xf0, 0x32, 0x7c, 0x15, 0x3c, 0x48, 0xab, 0x98, 0xae, 0x07, 0xf7, 0x16, 0xf6, 0x96,
	0xe0, 0xd2, 0xca, 0xe9, 0x71, 0xf0, 0x6e, 0xad, 0x4c, 0xea, 0x5b, 0xd8, 0x5b, 0x3a, 0x99, 0x16,
	0x8b, 0xf7, 0x20, 0xb1, 0x05, 0x5b, 0xa3, 0x23, 0x6b, 0x90, 0xd7, 0x87, 0x8f, 0x43, 0x87, 0x22,
	0x89, 0xd8, 0x13, 0xdc, 0xc5, 0xa4, 0x7d, 0x7f, 0x6f, 0x13, 0xc7, 0xdf, 0x3f, 0x7c, 0x49, 0xfe,
	0x43, 0x80, 0xe7, 0x1c, 0x07, 0x69, 0x35, 0x45, 0x0d, 0xf2, 0x9d, 0xb1, 0x63, 0x3e, 0xf8, 0x5e,
	0x3d, 0x21, 0xac, 0xad, 0xd8, 0xc8, 0xc5, 0xd6, 0xf6, 0xeb, 0x7f, 0x05, 0xdf, 0x39, 0xda, 0x80,
	0x62, 0xb7, 0x75, 0xd9, 0x6a, 0x7f, 0xdf, 0xaa, 0x66, 0x5c, 0xc1, 0xe8, 0x9e, 0x9f, 0xab, 0x86,
	0x51, 0x15, 0x5c, 0xe1, 0x42, 0xd1, 0xf4, 0x2e, 0x56, 0xab, 0x59, 0xb4, 0x05, 0xcf, 0x0c, 0x15,
	0xf7, 0xb4, 0x73, 0xb5, 0xaf, 0x62, 0xdc, 0xc6, 0xd5, 0x1c, 0x42, 0x50, 0xb9, 0x56, 0xb0, 0x72,
	0x65, 0xf4, 0xb5, 0x56, 0x4f, 0xd1, 0xb5, 0x66, 0x35, 0x8f, 0xb6, 0x61, 0x53, 0xd3, 0x75, 0xf5,
	0xb5, 0xa2, 0xf7, 0xb1, 0xfa, 0xa6, 0xab, 0x1a, 0x9d, 0x6a, 0xc1, 0x55, 0xea, 0xca, 0x99, 0xaa,
	0xf7, 0x5b, 0xed, 0x4e, 0x5f, 0xbd, 0xd1, 0x8c, 0x4e, 0xb5, 0xe8, 0xde, 0xee, 0x1a, 0x2a, 0x66,
	0x74, 0x25, 0xb4, 0x07, 0xdb, 0x54, 0xa7, 0xe8, 0x58, 0x55, 0x9a, 0xb7, 0x9e, 0xde, 0xa8, 0x96,
	0x43, 0x43, 0x4f, 0xc5, 0xda, 0xc5, 0x6d, 0x3f, 0xa0, 0x05, 0x48, 0x82, 0x9a, 0x07, 0x1d, 0xb9,
	0xb2, 0xe1, 0x5a, 0x9a, 0x67, 0xfd, 0xf6, 0xb5, 0x8a, 0x95, 0x8e, 0xd6, 0x6e, 0xf5, 0x2f, 0x94,
	0x0e, 0xbd, 0xf3, 0xd9, 0xe9, 0xdf, 0x65, 0x28, 0x2a, 0x77, 0x77, 0xe3, 0xe9, 0xc8, 0x41, 0x5a,
	0xb0, 0xde, 0xd2, 0x1f, 0x06, 0x2f, 0xe6, 0xc9, 0x5a, 0xda, 0x48, 0xeb, 0x2f, 0xf9, 0x46, 0xaf,
	0x98, 0x72, 0x06, 0x61, 0x78, 0xb6, 0xb0, 0x98, 0xa1, 0xfd, 0xf9, 0x05, 0xde, 0x66, 0x57, 0xff,
	0x22, 0xd6, 0x1e, 0x62, 0x76, 0xa1, 0xb2, 0xb8, 0x62, 0x20, 0xe6, 0x12, 0x77, 0x11, 0xab, 0x37,
	0xe2, 0x0f, 0xb0, 0xb0, 0x8b, 0x5b, 0x03, 0x0b, 0xcb, 0x5d, 0x3c, 0x58, 0x58, 0xfe, 0xc2, 0x21,
	0x67, 0xd0, 0x00, 0xb6, 0x39, 0x4b, 0x19, 0x3a, 0xe4, 0xc6, 0x19, 0x99, 0x69, 0xf5, 0xa3, 0x15,
	0xa7, 0x42, 0x2f, 0x8f, 0xec, 0xda, 0xc5, 0x8e, 0x66, 0xf4, 0x8a, 0x17, 0x3a, 0x67, 0x13, 0xa8,
	0x1f, 0xaf, 0x3e, 0xc8, 0xba, 0xe3, 0x6f, 0x02, 0xac, 0xbb, 0xc4, 0xc5, 0x83, 0x75, 0x97, 0xbc,
	0x54, 0xc8, 0x19, 0xf4, 0x1b, 0xbc, 0x4c, 0x1a, 0xd1, 0xe8, 0x9b, 0x64, 0xac, 0x68, 0x56, 0x4f,
	0xd6, 0x3d, 0xce, 0xf6, 0xc6, 0xe2, 0x10, 0x43, 0xd1, 0x3e, 0x8d, 0x3e, 0xd9, 0x6c, 0x6f, 0xf0,
	0xe7, 0x9f, 0x9c, 0x41, 0x37, 0xb0, 0x19, 0x19, 0x26, 0x68, 0xa9, 0x53, 0x97, 0x80, 0xbf, 0x4c,
	0x38, 0xc1, 0x22, 0x47, 0x06, 0x04, 0x5a, 0x6a, 0xd6, 0x24, 0xe4, 0x98, 0xe9, 0x22, 0x67, 0xd0,
	0x7b, 0xd8, 0x5a, 0x7a, 0xbd, 0x91, 0xcc, 0x0f, 0x96, 0x9d, 0x1d, 0xf5, 0x83, 0xc4, 0x33, 0x21,
	0xbe, 0x19, 0xfc, 0x92, 0x5c, 0x70, 0x70, 0x10, 0x7d, 0x67, 0x78, 0x1e, 0x0e, 0x93, 0x0f, 0x05,
	0x2e, 0x3e, 0x14, 0xe8, 0x3f, 0x6d, 0xbe, 0xfd, 0x2f, 0x00, 0x00, 0xff, 0xff, 0xb2, 0x98, 0x8f,
	0x14, 0xc6, 0x11, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AccountClient is the client API for Account service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AccountClient interface {
	// 用户操作
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error)
	QueryUserByID(ctx context.Context, in *QueryUserByIDRequest, opts ...grpc.CallOption) (*QueryUserByIDResponse, error)
	UpdateUserByID(ctx context.Context, in *UpdateUserByIDRequest, opts ...grpc.CallOption) (*UpdateUserByIDResponse, error)
	DeleteUserByID(ctx context.Context, in *DeleteUserByIDRequest, opts ...grpc.CallOption) (*DeleteUserByIDResponse, error)
	QueryUserByUsername(ctx context.Context, in *QueryUserByUsernameRequest, opts ...grpc.CallOption) (*QueryUserByUsernameResponse, error)
	UpdateUserPasswordByID(ctx context.Context, in *UpdateUserPasswordByIDRequest, opts ...grpc.CallOption) (*UpdateUserPasswordByIDResponse, error)
	VerifyUserPasswordByID(ctx context.Context, in *VerifyUserPasswordByIDRequest, opts ...grpc.CallOption) (*VerifyUserPasswordByIDResponse, error)
	VerifyUserPasswordByUsername(ctx context.Context, in *VerifyUserPasswordByUsernameRequest, opts ...grpc.CallOption) (*VerifyUserPasswordByUsernameResponse, error)
	// 标签操作
	QueryLabelByID(ctx context.Context, in *QueryLabelByIDRequest, opts ...grpc.CallOption) (*QueryLabelByIDResponse, error)
	UpdateLabelByID(ctx context.Context, in *UpdateLabelByIDRequest, opts ...grpc.CallOption) (*UpdateLabelByIDResponse, error)
	DeleteLabelByID(ctx context.Context, in *DeleteLabelByIDRequest, opts ...grpc.CallOption) (*DeleteLabelByIDResponse, error)
	QueryLabelByOwner(ctx context.Context, in *QueryLabelByOwnerRequest, opts ...grpc.CallOption) (*QueryLabelByOwnerResponse, error)
	CreateLabelByOwner(ctx context.Context, in *CreateLabelByOwnerRequest, opts ...grpc.CallOption) (*CreateLabelByOwnerResponse, error)
}

type accountClient struct {
	cc *grpc.ClientConn
}

func NewAccountClient(cc *grpc.ClientConn) AccountClient {
	return &accountClient{cc}
}

func (c *accountClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error) {
	out := new(CreateUserResponse)
	err := c.cc.Invoke(ctx, "/standard.Account/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) QueryUserByID(ctx context.Context, in *QueryUserByIDRequest, opts ...grpc.CallOption) (*QueryUserByIDResponse, error) {
	out := new(QueryUserByIDResponse)
	err := c.cc.Invoke(ctx, "/standard.Account/QueryUserByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) UpdateUserByID(ctx context.Context, in *UpdateUserByIDRequest, opts ...grpc.CallOption) (*UpdateUserByIDResponse, error) {
	out := new(UpdateUserByIDResponse)
	err := c.cc.Invoke(ctx, "/standard.Account/UpdateUserByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) DeleteUserByID(ctx context.Context, in *DeleteUserByIDRequest, opts ...grpc.CallOption) (*DeleteUserByIDResponse, error) {
	out := new(DeleteUserByIDResponse)
	err := c.cc.Invoke(ctx, "/standard.Account/DeleteUserByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) QueryUserByUsername(ctx context.Context, in *QueryUserByUsernameRequest, opts ...grpc.CallOption) (*QueryUserByUsernameResponse, error) {
	out := new(QueryUserByUsernameResponse)
	err := c.cc.Invoke(ctx, "/standard.Account/QueryUserByUsername", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) UpdateUserPasswordByID(ctx context.Context, in *UpdateUserPasswordByIDRequest, opts ...grpc.CallOption) (*UpdateUserPasswordByIDResponse, error) {
	out := new(UpdateUserPasswordByIDResponse)
	err := c.cc.Invoke(ctx, "/standard.Account/UpdateUserPasswordByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) VerifyUserPasswordByID(ctx context.Context, in *VerifyUserPasswordByIDRequest, opts ...grpc.CallOption) (*VerifyUserPasswordByIDResponse, error) {
	out := new(VerifyUserPasswordByIDResponse)
	err := c.cc.Invoke(ctx, "/standard.Account/VerifyUserPasswordByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) VerifyUserPasswordByUsername(ctx context.Context, in *VerifyUserPasswordByUsernameRequest, opts ...grpc.CallOption) (*VerifyUserPasswordByUsernameResponse, error) {
	out := new(VerifyUserPasswordByUsernameResponse)
	err := c.cc.Invoke(ctx, "/standard.Account/VerifyUserPasswordByUsername", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) QueryLabelByID(ctx context.Context, in *QueryLabelByIDRequest, opts ...grpc.CallOption) (*QueryLabelByIDResponse, error) {
	out := new(QueryLabelByIDResponse)
	err := c.cc.Invoke(ctx, "/standard.Account/QueryLabelByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) UpdateLabelByID(ctx context.Context, in *UpdateLabelByIDRequest, opts ...grpc.CallOption) (*UpdateLabelByIDResponse, error) {
	out := new(UpdateLabelByIDResponse)
	err := c.cc.Invoke(ctx, "/standard.Account/UpdateLabelByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) DeleteLabelByID(ctx context.Context, in *DeleteLabelByIDRequest, opts ...grpc.CallOption) (*DeleteLabelByIDResponse, error) {
	out := new(DeleteLabelByIDResponse)
	err := c.cc.Invoke(ctx, "/standard.Account/DeleteLabelByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) QueryLabelByOwner(ctx context.Context, in *QueryLabelByOwnerRequest, opts ...grpc.CallOption) (*QueryLabelByOwnerResponse, error) {
	out := new(QueryLabelByOwnerResponse)
	err := c.cc.Invoke(ctx, "/standard.Account/QueryLabelByOwner", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) CreateLabelByOwner(ctx context.Context, in *CreateLabelByOwnerRequest, opts ...grpc.CallOption) (*CreateLabelByOwnerResponse, error) {
	out := new(CreateLabelByOwnerResponse)
	err := c.cc.Invoke(ctx, "/standard.Account/CreateLabelByOwner", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountServer is the server API for Account service.
type AccountServer interface {
	// 用户操作
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
	QueryUserByID(context.Context, *QueryUserByIDRequest) (*QueryUserByIDResponse, error)
	UpdateUserByID(context.Context, *UpdateUserByIDRequest) (*UpdateUserByIDResponse, error)
	DeleteUserByID(context.Context, *DeleteUserByIDRequest) (*DeleteUserByIDResponse, error)
	QueryUserByUsername(context.Context, *QueryUserByUsernameRequest) (*QueryUserByUsernameResponse, error)
	UpdateUserPasswordByID(context.Context, *UpdateUserPasswordByIDRequest) (*UpdateUserPasswordByIDResponse, error)
	VerifyUserPasswordByID(context.Context, *VerifyUserPasswordByIDRequest) (*VerifyUserPasswordByIDResponse, error)
	VerifyUserPasswordByUsername(context.Context, *VerifyUserPasswordByUsernameRequest) (*VerifyUserPasswordByUsernameResponse, error)
	// 标签操作
	QueryLabelByID(context.Context, *QueryLabelByIDRequest) (*QueryLabelByIDResponse, error)
	UpdateLabelByID(context.Context, *UpdateLabelByIDRequest) (*UpdateLabelByIDResponse, error)
	DeleteLabelByID(context.Context, *DeleteLabelByIDRequest) (*DeleteLabelByIDResponse, error)
	QueryLabelByOwner(context.Context, *QueryLabelByOwnerRequest) (*QueryLabelByOwnerResponse, error)
	CreateLabelByOwner(context.Context, *CreateLabelByOwnerRequest) (*CreateLabelByOwnerResponse, error)
}

// UnimplementedAccountServer can be embedded to have forward compatible implementations.
type UnimplementedAccountServer struct {
}

func (*UnimplementedAccountServer) CreateUser(ctx context.Context, req *CreateUserRequest) (*CreateUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}
func (*UnimplementedAccountServer) QueryUserByID(ctx context.Context, req *QueryUserByIDRequest) (*QueryUserByIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryUserByID not implemented")
}
func (*UnimplementedAccountServer) UpdateUserByID(ctx context.Context, req *UpdateUserByIDRequest) (*UpdateUserByIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUserByID not implemented")
}
func (*UnimplementedAccountServer) DeleteUserByID(ctx context.Context, req *DeleteUserByIDRequest) (*DeleteUserByIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteUserByID not implemented")
}
func (*UnimplementedAccountServer) QueryUserByUsername(ctx context.Context, req *QueryUserByUsernameRequest) (*QueryUserByUsernameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryUserByUsername not implemented")
}
func (*UnimplementedAccountServer) UpdateUserPasswordByID(ctx context.Context, req *UpdateUserPasswordByIDRequest) (*UpdateUserPasswordByIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUserPasswordByID not implemented")
}
func (*UnimplementedAccountServer) VerifyUserPasswordByID(ctx context.Context, req *VerifyUserPasswordByIDRequest) (*VerifyUserPasswordByIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyUserPasswordByID not implemented")
}
func (*UnimplementedAccountServer) VerifyUserPasswordByUsername(ctx context.Context, req *VerifyUserPasswordByUsernameRequest) (*VerifyUserPasswordByUsernameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyUserPasswordByUsername not implemented")
}
func (*UnimplementedAccountServer) QueryLabelByID(ctx context.Context, req *QueryLabelByIDRequest) (*QueryLabelByIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryLabelByID not implemented")
}
func (*UnimplementedAccountServer) UpdateLabelByID(ctx context.Context, req *UpdateLabelByIDRequest) (*UpdateLabelByIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateLabelByID not implemented")
}
func (*UnimplementedAccountServer) DeleteLabelByID(ctx context.Context, req *DeleteLabelByIDRequest) (*DeleteLabelByIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteLabelByID not implemented")
}
func (*UnimplementedAccountServer) QueryLabelByOwner(ctx context.Context, req *QueryLabelByOwnerRequest) (*QueryLabelByOwnerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryLabelByOwner not implemented")
}
func (*UnimplementedAccountServer) CreateLabelByOwner(ctx context.Context, req *CreateLabelByOwnerRequest) (*CreateLabelByOwnerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateLabelByOwner not implemented")
}

func RegisterAccountServer(s *grpc.Server, srv AccountServer) {
	s.RegisterService(&_Account_serviceDesc, srv)
}

func _Account_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/standard.Account/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Account_QueryUserByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryUserByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).QueryUserByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/standard.Account/QueryUserByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).QueryUserByID(ctx, req.(*QueryUserByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Account_UpdateUserByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).UpdateUserByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/standard.Account/UpdateUserByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).UpdateUserByID(ctx, req.(*UpdateUserByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Account_DeleteUserByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).DeleteUserByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/standard.Account/DeleteUserByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).DeleteUserByID(ctx, req.(*DeleteUserByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Account_QueryUserByUsername_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryUserByUsernameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).QueryUserByUsername(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/standard.Account/QueryUserByUsername",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).QueryUserByUsername(ctx, req.(*QueryUserByUsernameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Account_UpdateUserPasswordByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserPasswordByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).UpdateUserPasswordByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/standard.Account/UpdateUserPasswordByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).UpdateUserPasswordByID(ctx, req.(*UpdateUserPasswordByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Account_VerifyUserPasswordByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyUserPasswordByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).VerifyUserPasswordByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/standard.Account/VerifyUserPasswordByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).VerifyUserPasswordByID(ctx, req.(*VerifyUserPasswordByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Account_VerifyUserPasswordByUsername_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyUserPasswordByUsernameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).VerifyUserPasswordByUsername(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/standard.Account/VerifyUserPasswordByUsername",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).VerifyUserPasswordByUsername(ctx, req.(*VerifyUserPasswordByUsernameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Account_QueryLabelByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryLabelByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).QueryLabelByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/standard.Account/QueryLabelByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).QueryLabelByID(ctx, req.(*QueryLabelByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Account_UpdateLabelByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateLabelByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).UpdateLabelByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/standard.Account/UpdateLabelByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).UpdateLabelByID(ctx, req.(*UpdateLabelByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Account_DeleteLabelByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteLabelByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).DeleteLabelByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/standard.Account/DeleteLabelByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).DeleteLabelByID(ctx, req.(*DeleteLabelByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Account_QueryLabelByOwner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryLabelByOwnerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).QueryLabelByOwner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/standard.Account/QueryLabelByOwner",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).QueryLabelByOwner(ctx, req.(*QueryLabelByOwnerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Account_CreateLabelByOwner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLabelByOwnerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).CreateLabelByOwner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/standard.Account/CreateLabelByOwner",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).CreateLabelByOwner(ctx, req.(*CreateLabelByOwnerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Account_serviceDesc = grpc.ServiceDesc{
	ServiceName: "standard.Account",
	HandlerType: (*AccountServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _Account_CreateUser_Handler,
		},
		{
			MethodName: "QueryUserByID",
			Handler:    _Account_QueryUserByID_Handler,
		},
		{
			MethodName: "UpdateUserByID",
			Handler:    _Account_UpdateUserByID_Handler,
		},
		{
			MethodName: "DeleteUserByID",
			Handler:    _Account_DeleteUserByID_Handler,
		},
		{
			MethodName: "QueryUserByUsername",
			Handler:    _Account_QueryUserByUsername_Handler,
		},
		{
			MethodName: "UpdateUserPasswordByID",
			Handler:    _Account_UpdateUserPasswordByID_Handler,
		},
		{
			MethodName: "VerifyUserPasswordByID",
			Handler:    _Account_VerifyUserPasswordByID_Handler,
		},
		{
			MethodName: "VerifyUserPasswordByUsername",
			Handler:    _Account_VerifyUserPasswordByUsername_Handler,
		},
		{
			MethodName: "QueryLabelByID",
			Handler:    _Account_QueryLabelByID_Handler,
		},
		{
			MethodName: "UpdateLabelByID",
			Handler:    _Account_UpdateLabelByID_Handler,
		},
		{
			MethodName: "DeleteLabelByID",
			Handler:    _Account_DeleteLabelByID_Handler,
		},
		{
			MethodName: "QueryLabelByOwner",
			Handler:    _Account_QueryLabelByOwner_Handler,
		},
		{
			MethodName: "CreateLabelByOwner",
			Handler:    _Account_CreateLabelByOwner_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "standard.proto",
}
