package errors

const (
	USER_NOT_EXIST      = "USER_NOT_EXIST"      // 用户不存在
	USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS" // 用户已经存在

	PERMISSION_RULE_NOT_EXIST      = "PERMISSION_RULE_NOT_EXIST"      // 权限不存在
	PERMISSION_RULE_ALREADY_EXISTS = "PERMISSION_RULE_ALREADY_EXISTS" // 权限已经存在

	PERMISSION_RESOURCE_NOT_EXIST      = "PERMISSION_RESOURCE_NOT_EXIST"      // 权限资源不存在
	PERMISSION_RESOURCE_ALREADY_EXISTS = "PERMISSION_RESOURCE_ALREADY_EXISTS" // 权限资源已经存在
)
