language: go
go:
  - master

# 允许执行的分支
branches:
  only:
  - master
  - develop

addons:
  ssh_known_hosts:
  - 132.232.106.236:44

# 预执行脚本
before_install:
  # 安装依赖
  - go get -v -d google.golang.org/grpc
  - go get -v -d github.com/jmoiron/sqlx
  - go get -v -d github.com/go-sql-driver/mysql
  - go get -v -d github.com/yinxulai/goutils/...
  - go get -v -d github.com/golang/protobuf/proto

install:
  # 编译
  - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o ./deploy/server ./main.go
  - sudo chmod -R 744 ./deploy # 赋予执行权限

before_deploy:
  # 准备服务器的 ssh_key
  - git clone https://github.com/yinxulai/keystore.git ./keystore
  - cd ./keystore
  - ./crypt.sh -d $pass_k $pass_iv
  - ./deploy.sh server root 132.232.106.236 44 deploy.key
  - cd ../deploy
  - tar -zcvf ./deploy.tar.gz ./* # 压缩档案 scp 加速

deploy:
  # 上传服务器
  provider: script
  skip_cleanup: true
  script: scp -prC ./deploy.tar.gz server:/www/grpcbrick/account
  on:
    branch: master

after_deploy:
  # 执行脚本
  - ssh -tt server "cd /www/grpcbrick/account; tar -zxvf .deploy.tar.gz .; rm -rf ./deploy.tar.gz" # 解压 
  - ssh -tt server "cd /www/grpcbrick/account/deploy; ./init.sh && ./start.sh;" # 执行部署脚本
