language: go
go:
  - master

# 允许执行的分支
branches:
  only:
  - master
  - develop

# 预执行脚本
before_install:
  # 安装依赖
  - go get -v -d google.golang.org/grpc
  - go get -v -d github.com/jmoiron/sqlx
  - go get -v -d github.com/go-sql-driver/mysql
  - go get -v -d github.com/yinxulai/goutils/...
  - go get -v -d github.com/golang/protobuf/proto

install:
  # 编译
  - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o ./deploy/account ./main.go

script: skip
