language: go
go:
  - master

# 允许执行的分支
branches:
  only:
    - master
    - /v\d+\.\d+\..*/

addons:
  ssh_known_hosts:
  - 132.232.106.236:44

# 预执行脚本
before_install:
  # 安装依赖
  - go get -v -d google.golang.org/grpc
  - go get -v -d github.com/jmoiron/sqlx
  - go get -v -d github.com/go-sql-driver/mysql
  - go get -v -d github.com/yinxulai/goutils/...
  - go get -v -d github.com/golang/protobuf/proto

install: skip

before_script: skip

script:
  # 编译
  - mkdir build ; cd build ;
  - CGO_ENABLED=0 GOOS=freebsd GOARCH=arm go build -o ./freebsd_arm/account ../main.go ; tar -zcvf ./freebsd_arm.tar.gz ./freebsd_arm ;
  - CGO_ENABLED=0 GOOS=freebsd GOARCH=386 go build -o ./freebsd_386/account ../main.go ; tar -zcvf ./freebsd_386.tar.gz ./freebsd_386 ;
  - CGO_ENABLED=0 GOOS=freebsd GOARCH=amd64 go build -o ./freebsd_amd64/account ../main.go ; tar -zcvf ./freebsd_amd64.tar.gz ./freebsd_amd64 ;

  - CGO_ENABLED=0 GOOS=linux GOARCH=arm go build -o ./linux_arm/account ../main.go ; tar -zcvf ./linux_arm.tar.gz ./linux_arm ;
  - CGO_ENABLED=0 GOOS=linux GOARCH=386 go build -o ./linux_386/account ../main.go ; tar -zcvf ./linux_386.tar.gz ./linux_386 ;
  - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o ./linux_amd64/account ../main.go ; tar -zcvf ./linux_amd64.tar.gz ./linux_amd64 ;

  - CGO_ENABLED=0 GOOS=darwin GOARCH=386 go build -o ./darwin_386/account ../main.go ; tar -zcvf ./darwin_386.tar.gz ./darwin_386 ;
  - CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -o ./darwin_amd64/account ../main.go ; tar -zcvf ./darwin_amd64.tar.gz ./darwin_amd64 ;

  - CGO_ENABLED=0 GOOS=windows GOARCH=386 go build -o ./windows_386/account ../main.go ; tar -zcvf ./windows_386.tar.gz ./windows_386 ;
  - CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -o ./windows_amd64/account ../main.go ; tar -zcvf ./windows_amd64.tar.gz ./windows_amd64 ;

  - cd ../

before_deploy:
  # 准备服务器的 ssh_key
  - git clone https://github.com/yinxulai/keystore.git ./keystore ;
  - cd ./keystore ;
  - ./crypt.sh -d $pass_k $pass_iv ; # 解密所有的 key
  - export GITHUB_TOKEN=`cat ./github.token.key ;` ; # 拿到 GITHUB_TOKEN
  - ./deploy.sh server root 132.232.106.236 44 deploy.key ; # 部署配置 SSH 服务，方便下面通过别名直接连接服务器
  - cd ../deploy ; tar -zcvf ./deploy.tar.gz ./* ; cd ../ ; # 压缩档案

# 部署版本
deploy:
  - provider: releases
    overwrite: true
    skip_cleanup: true
    api_key: $GITHUB_TOKEN
    file:
      - ./build/freebsd_arm.tar.gz
      - ./build/freebsd_386.tar.gz
      - ./build/freebsd_amd64.tar.gz
      - ./build/linux_arm.tar.gz
      - ./build/linux_386.tar.gz
      - ./build/linux_amd64.tar.gz
      - ./build/darwin_386.tar.gz
      - ./build/darwin_amd64.tar.gz
      - ./build/windows_386.tar.gz
      - ./build/windows_amd64.tar.gz
    on:
      tags: true
      branch: /v\d+\.\d+\..*/

# 准备服务器环境及部署脚本。
after_deploy:
  # 执行脚本
  - scp ./deploy/deploy.tar.gz server:/www/grpcbrick/account ; #  上传部署脚本
  - ssh -tt server "cd /www/grpcbrick/account; tar -zxvf ./deploy.tar.gz . ; rm -rf ./deploy.tar.gz ;" ; # 解压
  - ssh -tt server "cd /www/grpcbrick/account/deploy ; ./init.sh && ./start.sh ;" ; # 执行部署脚本

after_script: skip
