language: go

go:
  - master

# 禁止执行的分支
branches:
  except:
  - legacy
  - experimental

# 允许执行的分支
branches:
  only:
  - master
  - stable

# 预执行脚本
before_install:
  - go get -v golang.org/x/lint/golint

install:

before_script:

# 执行编译
script:
  - go build -o ./bin/darwin-amd64 ./main.go

