language: go
go:
  - master

# 允许执行的分支
branches:
  only:
  - master

# 预执行脚本
before_install:
  # 安装依赖
  - go get -v golang.org/x/lint/golint

install:
  # 编译
  - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o ./deploy/account ./main.go

before_deploy:
  # 准备服务器的 ssh_key
  - git clone https://github.com/yinxulai/keystore.git ./keystore
  - cd ./keystore
  - ./crypt.sh -d $pass_k $pass_iv
  - ./deploy.sh server root 132.232.106.236 44 deploy.key
  - cd ../
  - rm -rf ./keystore

deploy:
  - scp -r ./deploy server:/www/grpcbrick/account
  - ssh -tt server "/www/grpcbrick/account/deploy/init.sh"
  - ssh -tt server "/www/grpcbrick/account/deploy/start.sh"
