service:
  port: 8080
logger:
  level: debug
database:
  uri: postgresql://postgres:password@localhost/account
admin:
  password: test
secrets:
  - key: BwRdL3Qj8NdMBBLS
    value: C2BmqmNydSDMfyKt
  - key: test2
    value: test2
