service:
  port: 8080
logger:
  level: debug
database:
  uri: postgresql://postgres:password@localhost/account
admin:
  password: test
secrets:
  - key: test
    value: test
  - key: test2
    value: test2
