version: '3.8'

# 创建虚拟网络
networks:
  dev-net:
    driver: bridge

services:
  # 开发环境
  workspace:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspaces:cached
    networks:
      - dev-net
    command: sleep infinity # 禁止容器自动关闭

  # 数据库
  postgresql:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    networks:
      - dev-net
