package code

const (
	USER_NOT_EXIST        = "USER_NOT_EXIST"
	USER_ALREADY_EXISTS   = "USER_ALREADY_EXISTS"
	USER_ALREADY_DISABLED = "USER_ALREADY_EXISTS"

	TOO_MANY_SECRETS = "TOO_MANY_SECRETS"
	USER_SECRET_NOT_EXIST = "USER_SECRET_NOT_EXIST"
	USER_SECRET_NOT_DISABLED = "USER_SECRET_NOT_DISABLED"

	SETTING_NOT_EXIST   = "SETTING_NOT_EXIST"
	SETTING_ALREADY_EXISTS = "SETTING_ALREADY_EXISTS"

	PERMISSION_ROLE_NOT_EXIST      = "PERMISSION_ROLE_NOT_EXIST"
	PERMISSION_ROLE_ALREADY_EXISTS = "PERMISSION_ROLE_ALREADY_EXISTS"

	PERMISSION_RESOURCE_IN_USE = "PERMISSION_RESOURCE_IN_USE"
	PERMISSION_RESOURCE_NOT_EXIST      = "PERMISSION_RESOURCE_NOT_EXIST"
	PERMISSION_RESOURCE_ALREADY_EXISTS = "PERMISSION_RESOURCE_ALREADY_EXISTS"

	PERMISSION_RESOURCE_RULE_NOT_EXIST      = "PERMISSION_RESOURCE_RULE_NOT_EXIST"
	PERMISSION_RESOURCE_RULE_ALREADY_EXISTS = "PERMISSION_RESOURCE_RULE_ALREADY_EXISTS"
)
